// Language translations for GTrans app

export const translations = {
  en: {
    // Common
    loading: 'Loading...',
    search: 'Search',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    download: 'Download',
    upload: 'Upload',
    uploading: 'Uploading...',
    submit: 'Submit',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    page: 'Page',
    of: 'of',
    showing: 'Showing',
    noDataFound: 'No data found',
    tryAdjustingFilters: 'Try adjusting your filters',

    // Dashboard
    clientDashboard: 'CLIENT',
    staffDashboard: 'STAFF',
    manageYourFundTransfers: 'Manage your fund transfers',
    manageOrdersClientsOperations: 'Manage orders, clients, and operations',
    publicSite: 'Public Site',
    myProfile: 'My Profile',
    logout: 'Logout',

    // Profile drawer
    profileTitle: 'My Profile',
    profileSubtitle: 'Account information and settings',
    accountInformation: 'Account Information',
    usernameLabel: 'Username',
    emailLabel: 'Email',
    roleLabel: 'Role',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    enterCurrentPassword: 'Enter current password',
    atLeast8Chars: 'At least 8 characters',
    repeatNewPassword: 'Repeat new password',
    savePassword: 'Save Password',
    saving: 'Saving…',
    passwordChangedSuccess: 'Password changed successfully',
    passwordChangeFailed: 'Failed to change password. Please try again.',
    currentPasswordIncorrect: 'Current password is incorrect',
    enterCurrentPasswordError: 'Please enter your current password',
    passwordMinLengthError: 'New password must be at least 8 characters',
    passwordsMismatch: 'Passwords do not match',

    // Statistics
    totalOrders: 'Total Orders',
    currentOrders: 'Current Orders',
    executed: 'Executed',
    cancelled: 'Cancelled',
    deleted: 'Deleted',

    // Modules
    createOrder: 'Create Order',
    initiateFundTransfer: 'Initiate new fund transfer',
    accountOnHold: 'Account on hold - contact support',
    viewActiveOrders: 'View active orders in progress',
    viewCompletedOrders: 'View completed orders',
    viewCancelledOrders: 'View cancelled orders',
    viewDeletedOrders: 'View deleted orders',
    executedOrders: 'Executed Orders',
    cancelledOrders: 'Cancelled Orders',
    deletedOrders: 'Deleted Orders',

    // Client Dashboard Sections
    history: 'History',
    requestsFromGTrans: 'Requests from GTrans',
    otherRequests: 'Other Requests',

    // Staff Dashboard
    administration: 'Administration',
    kyc: 'KYC',
    clients: 'Clients',
    manageClientAccounts: 'Manage client accounts',
    activeOrders: 'Active Orders',
    viewProcessActiveOrders: 'View and process active orders',
    payeerAccounts: 'Payeer Accounts',
    managePayerAccounts: 'Manage payer accounts by currency',
    kycDatabase: 'KYC Database',
    knowYourCustomer: 'Know Your Customer verification',
    kycOnboardingQueue: 'KYC Onboarding Queue',
    reviewClientKYC: 'Review client KYC submissions',
    clientRequestsManagement: 'Client Requests Management',
    manageClientBadges: 'Manage Client Badges',
    configureClientRequests: 'Configure which requests are visible to clients and manage account status',

    // Orders Page
    searchOrders: 'Search orders...',
    allStatuses: 'All Statuses',
    clickToViewDetails: 'Click on an order to view details',
    orderID: 'Order ID',
    date: 'Date',
    amount: 'Amount',
    beneficiary: 'Beneficiary',
    bank: 'Bank',
    status: 'Status',
    noOrdersFound: 'No orders found',
    rowsPerPage: 'Rows per page:',
    orders: 'orders',
    order: 'order',

    // Order Actions
    viewTerms: 'View Terms',
    review: 'Review',
    viewDetails: 'View Details',
    cancelSelected: 'Cancel Selected',
    deleteSelected: 'Delete Selected',
    terms: 'Terms',

    // Status
    created: 'Created',
    draft: 'Draft',
    check: 'Check',
    rejected: 'Rejected',
    pending_payment: 'Pending Payment',
    on_execution: 'On Execution',
    released: 'Released',

    // Staff Actions
    createTxtInstruction: 'Create TXT Instruction',
    markExecuted: 'Mark Executed',
    selected: 'selected',
    searchByOrderClient: 'Search by order, client, beneficiary, BIC...',
    filterByStatus: 'Filter by status',
    currency: 'Currency',
    all: 'All',
    clear: 'Clear',
    client: 'Client',
    invRcv: 'Inv Rcv',
    proof: 'Proof',
    nonM: 'Non-M',
    noActiveOrders: 'No active orders',

    // Documents
    salesContract: 'Sales Contract',
    invoice: 'Invoice',
    otherDocuments: 'Other Documents',
    paymentProof: 'Payment Proof',
    wordOrder: 'WORD Order',
    submitted: 'Submitted',
    uploadedBy: 'Uploaded by:',
    notUploadedYet: 'Not uploaded yet',
    downloadCurrentVersion: 'Download Current Version',
    downloadTemplate: 'Download Template',
    downloadDocument: 'Download Document',
    reUpload: 'Re-upload',
    staff: 'Staff',

    // Account Status
    accountOnHoldTitle: 'Account On Hold',
    accountOnHoldMessage: 'Your account is temporarily on hold. Please contact support for more information.',

    // KYC
    kycVerification: 'KYC Verification',
    kycStatus: 'Status',

    // Other Badges
    serviceAgreement: 'Service Agreement',

    // Additional Text
    clickToViewFullDetails: 'Click on any order to view full details',
    searchDeletedOrders: 'Search deleted orders...',
    searchCancelledOrders: 'Search cancelled orders...',
    searchClients: 'Search clients...',
    dateCreated: 'Date Created',
    noDeletedOrders: 'No deleted orders',
    noCancelledOrders: 'No cancelled orders',
    noExecutedOrders: 'No executed orders',
    transactionStatus: 'Transaction Status',
    actReport: 'Act Report',
    filterBySettled: 'Filter by settled',
    settled: 'Settled',
    notSettled: 'Not Settled',
    clientManagement: 'Client Management',
    addClient: 'Add Client',
    clientID: 'Client ID',
    name: 'Name',
    signStatus: 'Sign Status',
    accountStatus: 'Account Status',
    signed: 'Signed',
    sent: 'Sent',
    notSent: 'Not Sent',
    active: 'Active',
    inactive: 'Inactive',
    show: 'Show',
    kycReviewQueue: 'KYC Review Queue',
    reviewProcessClientKYC: 'Review and process client KYC submissions',
    searchByCompanyOrClient: 'Search by company or client name...',
    noKYCSubmissions: 'No KYC submissions pending review',
    companyNameNotProvided: 'Company Name Not Provided',
    unknown: 'Unknown',
    na: 'N/A',
    backToDashboard: 'Back to Dashboard',
    platformTerms: 'Platform Terms & Conditions',
    sla: 'Service Level Agreement (SLA)',
    dpa: 'Data Processing Agreement (DPA)',
    amlKycCompliance: 'AML/KYC & Compliance Annex',
    otherRequestSigning: 'Other Request for Signing',
    otherRequestSubmit: 'Other Request to Submit',
    comingSoon: 'Coming Soon',
    // Create Order Page
    createPaymentOrder: 'Create Payment Order',
    dashboard: 'Dashboard',
    exportCSV: 'Export CSV',
    invoiceRequired: 'Invoice Required',
    invoiceInstructions: 'To complete order processing, please send your invoice to:',
    uploadDocumentsOptional: 'Upload Documents (Optional)',
    uploadHereOrEmail: 'You can upload documents here or send them by email',
    uploadSalesContract: 'Upload Sales Contract',
    uploadInvoice: 'Upload Invoice',
    uploadOtherDocuments: 'Upload Other Documents',
    iAcceptThe: 'I accept the',
    termsAndConditions: 'Terms & Conditions',
    byCheckingBoxAgree:
      'By checking this box, you agree to comply with all terms, conditions, and applicable regulations.',
    sendOrder: 'Send the Order',
    processing: 'Processing...',
    openFullTermsPDF: 'Open Full Terms & Conditions (PDF)',
    keyPoints: 'Key Points:',
    copy: 'Copy',
    trackYourTransfer: 'Track your transfer status',
    newestFirst: 'Newest first',
    oldestFirst: 'Oldest first',
    noActiveOrders2: 'No active orders',
    tryClearing: 'Try clearing your search',
    searchOrdersOrBeneficiary: 'Search orders or beneficiary...',
    showingOf: 'Showing',
    rowsPerPageLabel: 'Rows per page:',
    pageOf: 'Page',
    noCancelledOrders2: 'No cancelled orders',
    noDeletedOrders2: 'No deleted orders',
    // AmountCurrencySection
    paymentAmount: 'Payment Amount',
    remittanceAmount: 'Remittance Amount *',
    remittanceCurrency: 'Remittance Currency *',
    sourceCurrency: 'Source Currency *',
    selectCurrency: 'Select currency',
    selectSourceCurrency: 'Select source currency',
    // BeneficiaryInfoSection
    beneficiaryInformation: 'Beneficiary Information',
    beneficiaryName: 'Beneficiary Name *',
    beneficiaryNameHint: "(Max 70 chars, Latin letters, digits, and /-?:().,'+)",
    beneficiaryNamePlaceholder: 'Full name of beneficiary',
    beneficiaryAddress: 'Beneficiary Address *',
    beneficiaryAddressHint: '(Max 105 chars, same rules as name)',
    beneficiaryAddressPlaceholder: 'Full address',
    beneficiaryCountry: 'Beneficiary Country *',
    selectCountry: 'Select country...',
    searchCountry: 'Search country...',
    noCountryFound: 'No country found.',
    characters: 'characters',
    // BankDetailsSection
    bankDetails: 'Bank Details',
    destinationAccount: 'Destination Account Number *',
    ibanRequired: '(IBAN format required)',
    accountFormat: '(5-35 chars, A-Z 0-9)',
    countryBank: 'Country (Bank) *',
    bicLabel: 'BIC (Bank) *',
    bicChars: '(8 or 11 characters)',
    searchOrEnterBIC: 'Search or enter BIC...',
    searchBIC: 'Search BIC...',
    noBICFound: 'No BIC found. You can enter manually:',
    enterBICManually: 'Enter BIC manually',
    confirm: 'Confirm',
    manualEntry: 'Enter manually',
    bankName: 'Bank Name *',
    bankAddress: 'Bank Address *',
    bankNamePlaceholder: 'Bank name',
    bankAddressPlaceholder: 'Full bank address',
    manualOverrideWarning: '⚠️ Manual override enabled. Bank details will be logged for review.',
    manualEntryNote: 'Manual entry - please fill Bank Name and Address below',
    // TransactionRemarkSection
    transactionRemark: 'Transaction Remark',
    templateMode: 'Template',
    manualMode: 'Manual',
    transactionRemarkLabel: 'Transaction Remark *',
    transactionRemarkChars: '(Max 500 chars)',
    enterTransactionRemark: 'Enter transaction remark...',
    templateLabel: 'Template:',
    paymentType: 'Payment Type',
    goods: 'Goods',
    documents: 'Documents',
    addDocument: 'Add Document',
    documentType: 'Document Type *',
    documentNumber: 'Document Number *',
    documentDate: 'Document Date *',
    preview: 'Preview:',
    fillFieldsPreview: 'Fill in the required fields to see preview...',
    paymentPlaceholder: 'Payment, partial payment',
    goodsPlaceholder: 'goods',
    characters500: '500 characters',
    // Common table/UI
    orderId: 'Order ID',
    amountLabel: 'Amount',
    beneficiaryLabel: 'Beneficiary',
    bankLabel: 'Bank',
    clientLabel: 'Client',
    pageLabel: 'Page',
    ofLabel: 'of',
    loadingDots: 'Loading...',
    loadingYourOrders: 'Loading your orders...',
    searchOrdersPlaceholder: 'Search orders...',
    searchOrdersBeneficiary: 'Search orders or beneficiary...',
    searchCancelledPlaceholder: 'Search cancelled orders...',
    searchDeletedPlaceholder: 'Search deleted orders...',
    tryClearingSearch: 'Try clearing your search',
    noneLabel: 'None',
    allOrders: 'All Orders',
    byClient: 'By Client',
    byStatus: 'By Status',
    settledLabel: 'Settled',
    notSettledLabel: 'Not Settled',
    naLabel: 'N/A',
    txStatus: 'Tx Status',
    invoiceLabel: 'Invoice',
    trackTransferStatus: 'Track your transfer status',
    avgLabel: 'avg',
    activeLabel: 'active',
    clearFilters: 'Clear',
    orderLabel: 'order',
    ordersLabel: 'orders',
    txStatusHeader: 'Transaction Status',
    selectOnExecution: 'Select On Execution',
    selectedLabel: 'selected',
    createTxt: 'Create TXT',
    deleteLabel: 'Delete',
    noOrdersLabel: 'No orders',
    searchActiveOrdersPlaceholder: 'Search by order, client, beneficiary, BIC...',
    invNum: 'Inv#',
    allCurrencies: 'All Currencies',
    // StaffActiveOrders dialogs
    unusualTransactionTitle: 'Unusual Transaction Detected',
    unusualTransactionDesc: 'is significantly above their historical average.',
    thisOrder: 'This order:',
    clientAvgLabel: 'Client avg:',
    deviationLabel: 'Deviation:',
    xAboveAverage: 'x above average',
    enhancedVerification: 'Please conduct a thorough review. Enhanced verification may be required.',
    proceedToReview: 'Proceed to Review',
    cancelLabel: 'Cancel',
    deleteOrdersTitle: 'Order(s)',
    deleteOrdersDesc: 'Are you sure you want to delete the selected orders? This action cannot be undone.',
    clientOrdersBadge: 'orders',
    // StaffExecutedOrders
    executedOrdersTitle: 'Executed Orders',
    // StaffDashboard
    staffLabel: 'STAFF',
    staffSubtitle: 'Manage orders, clients, and operations',
    administrationSection: 'Administration',
    ordersSection: 'Orders',
    kycSection: 'KYC',
    reportsSection: 'Reports',
    requestsSection: 'Requests',
    mod_clients_title: 'Clients',
    mod_clients_desc: 'Manage client accounts',
    mod_activeOrders_title: 'Active Orders',
    mod_activeOrders_desc: 'View and process active orders',
    mod_executedOrders_title: 'Executed Orders',
    mod_executedOrders_desc: 'View completed orders',
    mod_payeerAccounts_title: 'Payeer Accounts',
    mod_payeerAccounts_desc: 'Manage payer accounts by currency',
    mod_kycDatabase_title: 'KYC Database',
    mod_kycDatabase_desc: 'Know Your Customer verification database',
    mod_kycQueue_title: 'KYC Onboarding Queue',
    mod_kycQueue_desc: 'Review client KYC submissions',
    mod_transactionData_title: 'Transaction Data',
    mod_transactionData_desc: 'Full transaction database with sort, filter & Excel export',
    mod_customerData_title: 'Customer Data',
    mod_customerData_desc: 'Client & counterparty data with KYC fields & Excel export',
    mod_manageBadges_title: 'Manage Badges',
    mod_manageBadges_desc: 'Account status, KYC, and Service Agreement badges',
    mod_serviceAgreement_title: 'Service Agreement',
    mod_serviceAgreement_desc: 'Manage master documents and client submissions',
    // StaffClients
    clientManagementTitle: 'Client Management',
    clientsCountLabel: 'clients',
    searchClientsPlaceholder: 'Search clients...',
    clientIdColumn: 'Client ID',
    nameColumn: 'Name',
    signStatusColumn: 'Sign Status',
    accountStatusColumn: 'Account Status',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    signedStatus: 'Signed',
    sentStatus: 'Sent',
    notSentStatus: 'Not Sent',
    showLabel: 'Show:',
    noClientsFound: 'No clients found',
    editClientTitle: 'Edit Client',
    addNewClientTitle: 'Add New Client',
    clientInfoSection: 'Client Information',
    docSigningSection: 'Document & Signing',
    groupReferenceSection: 'Group & Reference',
    authCredentialsSection: 'Authorization Credentials',
    generatePassword: 'Generate Password',
    saveClient: 'Save Client',
    savingLabel: 'Saving...',
    deleteClientTitle: 'Delete Client',
    deleteClientDesc: 'Are you sure you want to delete this client? This action cannot be undone.',
    // StaffKYCQueue
    kycReviewQueueTitle: 'KYC Review Queue',
    kycReviewQueueSubtitle: 'Review and process client KYC submissions',
    searchKYCPlaceholder: 'Search by company or client name...',
    noKYCPending: 'No KYC submissions pending review',
    submittedAtLabel: 'Submitted:',
    reviewButton: 'Review',
    unknownLabel: 'Unknown',
    // StaffClients form fields
    fieldClientIdLabel: 'Client ID *',
    fieldClientNameLabel: 'Client Name *',
    fieldAlias1: 'Alias 1',
    fieldAlias2: 'Alias 2',
    fieldAlias3: 'Alias 3',
    fieldRegNumber: 'Registration Number (e.g. NIB)',
    fieldTaxNumber: 'Tax Number (e.g. NPWP)',
    fieldRegCountry: 'Registration Country',
    fieldDirectorName: 'Director Name',
    fieldEmail: 'Email *',
    fieldDocId: 'Document ID',
    fieldSigningStatus: 'Signing Status',
    fieldDateSigning: 'Date of Signing',
    fieldGroupId: 'Group ID',
    fieldGroupName: 'Group Name',
    fieldLastId: 'Last ID',
    fieldLogin: 'Login *',
    fieldPassword: 'Password *',
    fieldDescription: 'Description',
    phClientId: 'e.g., CL1',
    phClientName: 'Client name',
    phAltName1: 'Alternative name 1',
    phAltName2: 'Alternative name 2',
    phAltName3: 'Alternative name 3',
    phRegNumber: 'e.g. 1234567890123456789',
    phTaxNumber: 'e.g. 12.345.678.9-012.345',
    phCountry: 'Country',
    phDirectorName: 'Director name',
    phEmail: 'client@example.com',
    phDocId: 'e.g., AGG/1/20261201',
    phGroupId: 'e.g., 1',
    phGroupName: 'e.g., Group1',
    phLastRef: 'Last reference',
    phUsername: 'username',
    phAdditionalNotes: 'Additional notes',
    optNotSent: 'Not Sent',
    optSent: 'Sent',
    optSigned: 'Signed',
    pageOfLabel: 'of',
    // StaffTransactionReport
    transactionDataReport: 'Transaction Data Report',
    searchTransactionPlaceholder: 'Search ID, sender, recipient, currency…',
    allTypes: 'All Types',
    ingoing: 'Ingoing',
    outgoing: 'Outgoing',
    domestic: 'Domestic',
    allRisk: 'All Risk',
    riskLow: 'Low',
    riskMedium: 'Medium',
    riskHigh: 'High',
    downloadExcel: 'Download Excel',
    addRecord: 'Add Record',
    addCustomer: 'Add Customer',
    actionsLabel: 'Actions',
    prevLabel: 'Prev',
    nextLabel: 'Next',
    noRecordsFound: 'No records found',
    // StaffCustomerReport
    customerDataReport: 'Customer Data Report',
    searchCustomerPlaceholder: 'Search by name, tax number, director…',
    allCustomerTypes: 'All Types',
    allCodes: 'All Codes',
    pepAll: 'PEP: All',
    pepYes: 'PEP: Yes',
    pepNo: 'PEP: No',
    citizenshipAll: 'Citizenship: All',
    indonesianYes: 'Indonesian: Yes',
    indonesianNo: 'Indonesian: No',
    // ClientKYC
    backToDashboardBtn: 'Back to Dashboard',
    kycVerificationTitle: 'KYC Verification',
    kycVerificationDesc: 'Complete your Know Your Customer verification',
    kycStatusNotStarted: 'Not Started',
    kycStatusInProgress: 'In Progress',
    kycStatusUnderReview: 'Under Review',
    kycStatusApproved: 'Approved',
    kycStatusRejected: 'Rejected',
    kycStepCorporate: 'Corporate Details',
    kycStepDocuments: 'Documents',
    kycStepBanking: 'Banking Details',
    kycStepOwnership: 'Ownership',
    kycStepDeclaration: 'Declaration & Signature',
    previousBtn: 'Previous',
    saveProgressBtn: 'Save Progress',
    nextBtn: 'Next',
    submitKYCBtn: 'Submit KYC',
    riskAlert: 'Risk Alert',

    // ===== Client i18n batch =====
    // Validation (CreateOrder)
    valAmountRequired: 'Amount is required',
    valCurrencyRequired: 'Currency is required',
    valBeneficiaryCountryRequired: 'Beneficiary country is required',
    valAccountNumberRequired: 'Account number is required',
    valBankCountryRequired: 'Country is required',
    valBicRequired: 'BIC is required',
    valBankNameRequired: 'Bank name is required',
    valBankAddressRequired: 'Bank address is required',
    valTransactionRemarkRequired: 'Transaction remark is required',
    valEnableManualOverride: 'Enable manual override to fill bank details',
    valTermsRequired: 'Please accept the Terms & Conditions to proceed',
    valFixErrorsBeforeSubmit: 'Please fix all errors before submitting',
    valTransactionRemarkExceeds500: 'Transaction remark exceeds 500 characters',
    valAddAtLeastOneDocument: 'Please add at least one document',
    // CreateOrder toasts
    orderCreatedSuccess: 'Order created successfully!',
    failedCreateOrder: 'Failed to create order',
    emailCopiedToClipboard: 'Email copied to clipboard',
    subjectCopiedToClipboard: 'Subject copied to clipboard',
    documentSelected: 'Document selected',
    uploadedSuccessfully: 'uploaded successfully',
    failedUploadSomeDocuments: 'Failed to upload some documents',
    couldNotOpenTerms: 'Could not open Terms & Conditions',
    failedLoadTerms: 'Failed to load Terms & Conditions',
    // Terms paragraphs
    termsKeyPoint1: 'All fund transfers comply with Indonesian regulations including Anti-Money Laundering laws',
    termsKeyPoint2: 'PT GARUDA ARMA NUSA will execute transfers as mandated in signed Fund Transfer Orders',
    termsKeyPoint3: 'Orders must be submitted at least 1 hour before currency cut-off time',
    termsKeyPoint4: 'Payment must be received 30 minutes before cut-off time',
    termsKeyPoint5: 'Orders are valid only once on the stated date',
    termsKeyPoint6: 'Authorized signatories must be documented per Customer Data Form',
    termsRegulationsApplied: 'Regulations Applied:',
    termsRegulation1: 'Law No. 8/2010 - Prevention and Eradication of Money Laundering',
    termsRegulation2: 'Law No. 3/2011 - Fund Transfers',
    termsRegulation3: 'Law No. 9/2013 - Prevention of Terrorism Financing',
    termsRegulation4: 'Law No. 27/2022 - Personal Data Protection',
    termsRegulation5: 'Bank Indonesia Regulations on Payment Services',
    // Page titles / subtitles
    orderHistorySubtitle: 'Order History',
    saSubtitle: 'Service Agreement',
    submitNdaSubtitle: 'Submit NDA Document',
    // OrderHistory
    loadingOrdersText: 'Loading orders...',
    noOrdersYetTitle: 'No orders yet',
    createFirstOrderHint: 'Create your first remittance order to get started.',
    noOrdersMatchFilter: 'No orders match your current filters.',
    pageOfText: 'Page',
    ordersFoundText: 'found',
    // OrderFilters
    filtersLabel: 'Filters',
    filterSearchByOrderBeneficiaryBic: 'Search by Order ID, Beneficiary, BIC...',
    statusPlaceholder: 'Status',
    currencyPlaceholder: 'Currency',
    fromDatePlaceholder: 'From date',
    toDatePlaceholder: 'To date',
    clearFiltersBtnLabel: 'Clear filters',
    // Status labels (badges)
    statusUnderReviewLabel: 'Under Review',
    statusInProgressLabel: 'In Progress',
    statusCanceledLabel: 'Canceled',
    statusClientCanceledLabel: 'Client Canceled',
    statusCreatedDesc: 'Order placed, awaiting review',
    statusUnderReviewDesc: 'Our team is reviewing your order',
    statusPendingPaymentDesc: 'Awaiting your payment',
    statusInProgressDesc: 'Transfer is being processed',
    // OrderDetailsDrawer
    statusTimeline: 'Status Timeline',
    csvDownloadedToast: 'CSV downloaded',
    orderIdCopiedToast: 'Order ID copied',
    paymentDetails: 'Payment Details',
    drawerBeneficiarySection: 'Beneficiary',
    detailNameLabel: 'Name',
    detailAddressLabel: 'Address',
    detailAccountLabel: 'Account',
    detailBankNameLabel: 'Bank Name',
    detailBicSwiftLabel: 'BIC/SWIFT',
    detailCountryLabel: 'Country',
    downloadCsvBtn: 'Download CSV',
    // ClientNDA
    ndaInformationSavedToast: 'NDA information saved',
    ndaSubmittedForReviewToast: 'NDA submitted for review!',
    saveNdaFirst: 'Please save NDA information first',
    failedUploadFile: 'Failed to upload file',
    signedNdaUploadedToast: 'Signed NDA uploaded',
    ndaRequestTitle: 'NDA Request',
    ndaRequestSubtitle: 'Submit your Non-Disclosure Agreement information',
    partnerInformation: 'Partner Information',
    effectiveDateLabel: 'Effective Date *',
    partnerInnLabel: 'Partner INN',
    partnerNameRu: 'Partner Name (Russian) *',
    partnerNameEn: 'Partner Name (English) *',
    partnerAddressRu: 'Partner Address (Russian)',
    partnerAddressEn: 'Partner Address (English)',
    contactNameLabel: 'Contact Name',
    contactEmailLabel: 'Contact Email',
    contactPhoneLabel: 'Contact Phone',
    paperCopyRequired: 'Paper copy required',
    generatedNdaTitle: 'Generated NDA',
    downloadGeneratedNda: 'Download Generated NDA',
    uploadSignedNdaTitle: 'Upload Signed NDA',
    uploadSignedNdaBtnLabel: 'Upload Signed NDA',
    viewUploadedNda: 'View Uploaded NDA',
    saveProgressLabel: 'Save Progress',
    submitNdaLabel: 'Submit NDA',
    errorLoadingClient: 'Error loading client data',
    // ClientSubmitNDA
    ndaDocumentSubmissionTitle: 'NDA Document Submission',
    pleaseDownloadSignAndUpload: 'Please download, sign, and upload the NDA document.',
    ndaTemplateLabel: 'NDA Template',
    downloadSignAndUploadHint: 'Download this document, sign it, and upload below',
    documentSubmittedTitle: 'Document Submitted',
    ndaUnderReviewMsg: 'Your NDA has been submitted and is under review',
    viewSubmittedDocumentBtn: 'View Submitted Document',
    uploadSignedNdaPdfHelp: 'Upload the signed NDA document (PDF format)',
    selectFileBtn: 'Select File',
    statusColon: 'Status:',
    ndaUploadFailedToast: 'Upload failed',
    ndaUploadSuccessToast: 'NDA submitted successfully',
    // ClientServiceAgreement
    signedSaUploadSuccessToast: 'Signed Service Agreement uploaded successfully',
    failedToUploadDocumentToast: 'Failed to upload document',
    saGeneratedSuccessToast: 'Service Agreement generated successfully',
    failedGenerateSaToast: 'Failed to generate Service Agreement',
    agreementAcceptedTitle: 'Agreement Accepted',
    saAcceptedDesc: 'Your Service Agreement has been reviewed and accepted by GTrans.',
    underReviewTitle: 'Under Review',
    saUnderReviewDesc: 'Your signed Service Agreement is being reviewed by our team.',
    instructionsTitle: 'Instructions',
    saInstructionsDesc: 'Follow these steps to complete the Service Agreement',
    step1Heading: 'Download the Agreement',
    step1Desc: 'Click the download button below to get the Service Agreement document.',
    step2Heading: 'Review and Sign',
    step2Desc: 'Read the agreement carefully and sign it with authorized signatory.',
    step3Heading: 'Upload Signed Copy',
    step3Desc: 'Upload the signed agreement using the upload button below.',
    step1DownloadTitle: 'Step 1: Download Agreement',
    step2UploadTitle: 'Step 2: Upload Signed Agreement',
    saDocxDocument: 'DOCX Document',
    noteFromGtrans: 'Note from GTrans:',
    alternativeStaffDoc: 'Alternative document provided by staff:',
    downloadStaffDocument: 'Download Staff Document',
    signedAgreementUploaded: 'Signed Agreement Uploaded',
    yourSignedDocSubmitted: 'Your signed document has been submitted',
    viewLabelBtn: 'View',
    replaceLabelBtn: 'Replace',
    uploadSignedAgreementBtn: 'Upload Signed Agreement',
    generatingDots: 'Generating...',
    acceptedFormatsHint: 'Accepted formats: PDF, DOC, DOCX',
    saHeaderSubtitle: 'Download, sign, and upload the agreement',
    // KYC Corporate Details
    kycCompanyNameLabel: 'Company Name *',
    kycTradingNameLabel: 'Trading Name',
    kycIncorporationDateLabel: 'Incorporation Date',
    kycIncorporationCountryLabel: 'Incorporation Country',
    kycRegisteredAddressLabel: 'Registered Address *',
    kycTaxIdLabel: 'Tax ID',
    kycRegistrationNumberLabel: 'Registration Number',
    kycTelephoneLabel: 'Telephone',
    kycWebsiteLabel: 'Website',
    // KYC Documents
    kycSectionCompanyId: '2. Company Identification Details',
    kycDocumentsInstruction:
      'Please provide copies of the below documents. These documents should be provided in the English Language or with an English Translation.',
    kycMandatoryDocsHeader: 'Mandatory documents to be provided',
    kycUploadHeader: 'Upload',
    kycDocCertOfIncorporation: 'Certificate of Incorporation',
    kycDocTradeLicense: 'Trade License',
    kycDocCommitteeList: 'List Of Company Committee (Commissioners & Directors)',
    kycDocMemorandum: 'Memorandum/Articles of Association and Amendments',
    kycDocShareholdersList: 'List of Shareholder and capital share',
    kycDocAuthSignatories: 'List of Authorized signatories with signatures authentication',
    kycDocPassportSignatories: 'Copy of Passport for authorized signatories (2.6)',
    kycUploadedLabel: 'Uploaded',
    kycDownloadFailed: 'Download failed',
    kycFileUploadedSuccess: 'File uploaded successfully',
    kycFailedUploadFile: 'Failed to upload file',
    // KYC Banking
    kycBankingTitle: '3. Banking Details',
    kycBankingInstruction: 'Please provide the full banking details',
    kycPrincipalBankers: 'Principal Bankers (Name of the Bank)',
    kycSwiftBicLabel: 'Swift BIC',
    kycBankBranchAddress: 'Bank Branch Address Details',
    kycBankCityCountry: 'Bank City & Country',
    kycBankAccountName: 'Bank Account Name',
    kycBankAccountCurrency: 'Currency of Bank Account',
    kycBankAccountNumber: 'Bank Account Number/IBAN number',
    kycBankManagerContact: 'Name of Bank Account Manager & Contact Details',
    // KYC Ownership
    kycOwnershipTitle: '4. Ownership Information',
    kycAddShareholder: 'Add Shareholder',
    kycShareholderAddedToast: 'Shareholder added',
    kycShareholderRemovedToast: 'Shareholder removed',
    kycClientIdMissingToast: 'Client ID missing',
    kycFailedToUpdateToast: 'Failed to update',
    kycNoShareholdersYet: 'No shareholders added yet. Click "Add Shareholder" to begin.',
    kycShareholderLabel: 'Shareholder',
    kycShareholderNameLabel: 'Shareholder and UBO Name (As per Passport or License document)',
    kycShareholderNamePlaceholder: 'Enter shareholder name',
    kycShareholdingLabel: 'Shareholding %',
    kycNationalityResidence: 'Nationality and Country of Residence',
    kycNationalityPlaceholder: 'Nationality',
    // KYC Declaration
    kycDeclarationSection: '5. Declaration',
    kycDeclarationText:
      'It is hereby declared that the information and particulars furnished above are true and correct to the best of my/our knowledge and belief and that nothing has been misrepresented and/or concealed.',
    kycDeclarationConfirm: 'I confirm that I have read and agree to the declaration above *',
    kycSignatureSection: '6. Signature',
    kycAuthorizedPersonName: 'Name of authorized person completing this Registration Form *',
    kycDateColon: 'Date:',
    kycPositionLabel: 'Position',
    kycLocationColon: 'Location:',
    kycPowerOfAttorneyNote:
      'If Registration Form is filled by unauthorized person, please provide the Power of Attorney Letter',
    kycDownloadUploadHeader: 'Download & Upload Signed Document',
    kycDownloadKycForm: 'Download KYC Form (with prefilled data)',
    kycUploadSignedKycDoc: 'Upload Signed KYC Document',
    kycDocumentUploadedLabel: 'Document Uploaded',
    kycReplaceLabel: 'Replace',
    kycUploadSignedDocBtn: 'Upload Signed Document',
    kycSavingGenerating: 'Saving & Generating Document...',
    kycDocumentDownloaded: 'KYC document downloaded',
    kycFailedDownload: 'Failed to download KYC document',
    kycSignedDocUploadHelp: 'Please download the form above, sign it, and upload the scanned PDF.',
    kycClientIdMissingError: 'Client ID missing',
    // Remittance: BeneficiarySection
    beneficiaryDetailsTitle: 'Beneficiary Details',
    recipientNameLabel: 'Recipient Name *',
    recipientNamePlaceholder: 'Full name of recipient',
    beneficiaryAddressLabel: 'Beneficiary Address',
    beneficiaryAddressFullPlaceholder: 'Full address',
    beneficiaryCountryLabel: 'Country',
    beneficiaryCountryPlaceholder: 'Beneficiary country',
    registrationNumberLabel: 'Registration Number',
    registrationNumberPlaceholder: 'Tax ID or registration number',
    accountNumberIbanLabel: 'Account Number / IBAN',
    accountNumberIbanPlaceholder: 'Bank account number or IBAN',
    beneficiaryBankLabel: 'Beneficiary Bank',
    beneficiaryBankPlaceholder: 'Bank name',
    bicSwiftCodeLabel: 'BIC/SWIFT Code',
    bicIdentifierCodePlaceholder: 'Bank Identifier Code',
    bankAddressFieldLabel: 'Bank Address',
    bankAddressFullPlaceholder: 'Full bank address',
    // BankDetailsSection
    accountNumberPlainPlaceholder: 'Account number',
    // TransactionRemarkSection
    docNumberExamplePlaceholder: 'e.g., 24543',
    // InvoiceInfoModal
    orderCreatedSuccessTitle: 'Order Created Successfully!',
    sendYourInvoiceTitle: 'Send Your Invoice',
    sendInvoiceInstruction: 'To complete order processing, please send your invoice to:',
    emailAddressColon: 'Email Address:',
    emailSubjectColon: 'Email Subject:',
    orderInDraftMessage: 'Your order is currently in Draft status. It will be processed once we receive your invoice.',
    gotItButton: 'Got it',
    // ClientTermsDrawer
    termsSectionLabel: 'Terms',
    drawerAmountLabel: 'Amount',
    remunerationTypeLabel: 'Remuneration Type',
    remunerationPercentLabel: 'Remuneration %',
    remunerationFixedLabel: 'Remuneration Fixed',
    amountRemunerationLabel: 'Amount Remuneration',
    clientPaymentCurrencyLabel: 'Client Payment Currency',
    exchangeRateLabel: 'Exchange Rate',
    fvLabel: 'FV',
    remunerationLabel: 'Remuneration',
    totalUppercaseLabel: 'TOTAL',
    uploadPaymentProofLabel: 'Upload Payment Proof',
    uploadPaymentProofBtn: 'Upload Payment Proof',
    uploadingDots: 'Uploading...',
    uploadingShort: 'Uploading..',
    uploadedColon: 'Uploaded:',
    dataFixingLabel: 'Data Fixing',
    datePaidLabel: 'Date Paid',
    notPaidLabel: 'Not Paid',
    orderDocumentSection: 'Order Document',
    orderFromStaffLabel: 'Order (from Staff)',
    downloadUnsignedOrderBtn: 'Download Unsigned Order',
    noOrderDocAvailable: 'No order document available yet',
    uploadSignedOrderLabel: 'Upload Signed Order',
    uploadSignedOrderBtn: 'Upload Signed Order',
    signedOrderFromStaffLabel: 'Signed Order (from Staff)',
    downloadSignedOrderBtn: 'Download Signed Order',
    orderInformationSection: 'Order Information',
    beneficiaryNameColon: 'Beneficiary Name:',
    beneficiaryAddressColon: 'Beneficiary Address:',
    destinationAccountColon: 'Destination Account:',
    bankNameColon: 'Bank Name:',
    bicSwiftColon: 'BIC/SWIFT:',
    bankAddressColon: 'Bank Address:',
    countryColon: 'Country:',
    remarkColon: 'Remark:',
    payeerAccountInformation: 'Payeer Account Information',
    accountNameLabel: 'Account Name',
    accountNumberDrawerLabel: 'Account Number',
    drawerCurrencyLabel: 'Currency',
    bicLabelShort: 'BIC:',
    swiftLabelShort: 'SWIFT:',
    payeerIdLabel: 'Payeer ID:',
    cancelOrderBtn: 'Cancel Order',
    closeBtn: 'Close',
    cancelOrderTitle: 'Cancel Order?',
    cancelOrderDesc: 'This will mark the order as cancelled. This action can be reversed by staff.',
    noKeepIt: 'No, Keep It',
    yesCancelOrder: 'Yes, Cancel Order',
    deleteOrderTitle: 'Delete Order?',
    deleteOrderDesc: 'This will mark the order as deleted. Only rejected orders can be deleted.',
    yesDeleteOrder: 'Yes, Delete Order',
    toastOrderCancelled: 'Order cancelled',
    toastFailedCancelOrder: 'Failed to cancel order',
    toastOrderDeleted: 'Order deleted',
    toastFailedDeleteOrder: 'Failed to delete order',
    toastSignedOrderUploaded: 'Signed order uploaded successfully',
    toastFailedUploadSignedOrder: 'Failed to upload signed order',
    toastPaymentProofUploaded: 'Payment proof uploaded successfully',
    toastFailedUploadPaymentProof: 'Failed to upload payment proof',
    toastFailedDownloadDoc: 'Failed to download document',
    toastExcelDownloaded: 'Excel downloaded successfully',
    toastFailedDownloadExcel: 'Failed to download Excel',
    // ClientExecutedDrawer
    executedDetailsSubtitle: 'Details for executed order',
    transactionStatusUppercase: 'Transaction Status',
    statusReceivedLabel: 'Received',
    statusNotReceivedLabel: 'Not Received',
    drawerNumberLabel: 'Number',
    drawerDateLabel: 'Date',
    downloadTransactionStatusBtn: 'Download Transaction Status',
    mt103Title: 'MT103',
    downloadMt103Btn: 'Download MT103',
    actReportTitle: 'Act Report',
    actSignedLabel: 'Signed',
    actOnSignLabel: 'On Sign',
    actNotMadeLabel: 'Not Made',
    downloadActReportBtn: 'Download Act Report',
    downloadUnsignedActReportBtn: 'Download Unsigned Act Report',
    uploadSignedActReportLabel: 'Upload Signed Act Report',
    uploadSignedActReportBtn: 'Upload Signed Act Report',
    failedUploadActReportToast: 'Failed to upload Act Report',
    signedActReportUploadedToast: 'Signed Act Report uploaded successfully',
    failedDownloadUrlToast: 'Failed to get download URL',
    documentsHeader: 'Documents',
    salesContractDrawerLabel: 'Sales Contract',
    invoiceDrawerLabel: 'Invoice',
    otherDocumentsDrawerLabel: 'Other Documents',
    wordOrderDrawerLabel: 'WORD Order',
    signedWordOrderDrawerLabel: 'Signed WORD Order',
    downloadShortLabel: 'Download',
    remittanceCurrencyLabel: 'Remittance Currency',
    debitAccountLabel: 'Debit Account',
    transactionReferenceLabel: 'Transaction Reference',
    bankCountryLabel: 'Bank Country',
    bicSwiftLabel: 'BIC/SWIFT',
    bankNameDrawerLabel: 'Bank Name',
    bankAddressDrawerLabel: 'Bank Address',
    transactionRemarkDrawerLabel: 'Transaction Remark',
    beneficiaryNameDrawerLabel: 'Beneficiary Name',
    beneficiaryAddressDrawerLabel: 'Beneficiary Address',
    destinationAccountDrawerLabel: 'Destination Account',
    bankShortLabel: 'Bank',
    clientShortLabel: 'Client',
    beneficiaryShortLabel: 'Beneficiary',
    // ClientKYC page
    kycProgressSavedToast: 'Progress saved',
    kycFailedToSaveToast: 'Failed to save: ',
    kycSubmittedForReviewToast: 'KYC submitted for review!',
    kycFailedSubmitToast: 'Failed to submit: ',
    kycClientNotFound: 'Client not found. Please contact support.',
    kycSavingChangesFirst: 'Saving changes first...',

    // ===== Staff i18n batch =====
    // StaffKYC page
    staffKycHeaderTitle: 'KYC Database',
    staffKycHeaderSubtitle: 'Know Your Customer Verification',
    staffKycBackToResults: 'Back to results',
    staffKycSearchTitle: 'Search...',
    staffKycSearchPlaceholder: 'Search...',
    staffKycSearchAllData: 'Search All Data',
    staffKycIndividualTab: 'Individual',
    staffKycCorporateTab: 'Corporate',
    staffKycNoResultsFound: 'No results found',
    staffKycTypeLabelText: 'Type',
    staffKycSourceLabelText: 'Source',
    staffKycLoadDateLabelText: 'Load Date',
    staffKycTypeIndividual: 'Individual',
    staffKycTypeCorporate: 'Corporate',
    staffKycTitleLabel: 'Title',
    staffKycJobTitleLabel: 'Job Title',
    staffKycAliasLabel: 'Alias',
    staffKycNationalityLabel: 'Nationality',
    staffKycPassportLabel: 'Passport',
    staffKycIdentityNoLabel: 'Identity No',
    staffKycDobLabel: 'Date of Birth',
    staffKycPobLabel: 'Place of Birth',
    staffKycAdditionalNamesLabel: 'Additional Names',
    staffKycAddressLabel: 'Address',
    staffKycAdditionalInfoLabel: 'Additional Info',
    staffKycSourceListLabel: 'Source List',
    staffKycEntryTypeLabel: 'Entry Type',
    staffKycLoadDateField: 'Load Date',
    // StaffPayeerAccounts
    payeerAccountsTitle: 'Payeer Accounts',
    payeerGTransStaff: 'GTrans Staff',
    payeerAddAccount: 'Add Account',
    payeerCurrencyHeader: 'Currency',
    payeerAliasHeader: 'Alias',
    payeerAccountNumberHeader: 'Account Number',
    payeerBankNameHeader: 'Bank Name',
    payeerCountryHeader: 'Country',
    payeerStatusHeader: 'Status',
    payeerNoAccountsFound: 'No accounts found',
    payeerStatusActive: 'Active',
    payeerStatusInactive: 'Inactive',
    payeerEditAccount: 'Edit Account',
    payeerAddPayeerAccount: 'Add Payeer Account',
    payeerCurrencyLabel: 'Currency *',
    payeerAliasLabel: 'Alias',
    payeerAliasPlaceholder: 'Short name to identify this account',
    payeerAccountNumberLabel: 'Account Number *',
    payeerAccountNumberPlaceholder: 'Account number',
    payeerBankNameLabel: 'Bank Name',
    payeerBankNamePlaceholder: 'Bank name',
    payeerBankAddressLabel: 'Bank Address',
    payeerBankAddressPlaceholder: 'Bank address',
    payeerBankCorrAccountLabel: 'Bank Correspondent Account',
    payeerBankCorrAccountPlaceholder: 'Correspondent account',
    payeerBankBicLabel: 'Bank BIC/SWIFT',
    payeerBankBicPlaceholder: 'BIC/SWIFT code',
    payeerBankCountryLabel: 'Bank Country',
    payeerBankCountryPlaceholder: 'Select country',
    payeerActiveLabel: 'Active',
    payeerSavingDots: 'Saving...',
    payeerSaveBtn: 'Save',
    payeerCancelBtn: 'Cancel',
    payeerDeletingDots: 'Deleting...',
    payeerDeleteBtn: 'Delete',
    payeerAccountUpdated: 'Account updated',
    payeerAccountCreated: 'Account created',
    payeerAccountDeleted: 'Account deleted',
    payeerConfirmDelete: 'Are you sure you want to delete this account?',
    payeerFillRequired: 'Please fill all required fields',
    // StaffTransactionReport
    transTypePlaceholder: 'Type',
    transCurrencyPlaceholder: 'Currency',
    transRiskPlaceholder: 'Risk',
    transDttotPlaceholder: 'DTTOT',
    transDpppspmPlaceholder: 'DPPPSPM',
    // StaffCustomerReport
    custTypePlaceholder: 'Customer Type',
    custCodePlaceholder: 'Code Type',
    custPepPlaceholder: 'PEP',
    custCitizenshipPlaceholder: 'Citizenship',
    // StaffServiceAgreement
    saUpdatedSuccessfully: 'Updated successfully',
    saFailedToUpdate: 'Failed to update',
    saBadgeCreatedSuccess: 'Badge created successfully',
    saMasterDocUploaded: 'Master document uploaded',
    saFailedUploadMasterDoc: 'Failed to upload master document',
    saMasterAgreementGenerated: 'Master Agreement generated successfully',
    saFailedGenerateMaster: 'Failed to generate Master Agreement',
    saAddNotesPlaceholder: 'Add notes for client...',
    // StaffClientRequests
    crSearchClientsPlaceholder: 'Search clients...',
    crReasonForHoldPlaceholder: 'Reason for hold...',
    // StaffClients toasts
    clClientUpdatedToast: 'Client updated',
    clClientCreatedToast: 'Client created',
    clClientDeletedToast: 'Client deleted',
    clClientStatusUpdatedToast: 'Client status updated',
    clFailedSaveClientToast: 'Failed to save client',
    clFailedDeleteClientToast: 'Failed to delete client',
    // StaffActiveOrders
    aoOrdersDeletedToast: 'Orders deleted',
    aoStatusChangedToText: 'Status changed to',
    aoNoOrdersSelected: 'No orders selected',
    aoInstructionFileCreatedFor: 'Instruction file created for',
    aoOrderUpdatedToast: 'Order updated',
    // StaffComplyAdvantage
    caSearchFailedToast: 'Search failed',
    caSearchByNamePlaceholder: 'Search by name or external ID...',
    // StaffExecutedOrders
    eoOrderUpdatedToast: 'Order updated',
    // Staff drawers
    drKycDecisionRecorded: 'KYC decision recorded successfully',
    drFailedRecordDecision: 'Failed to record decision',
    drAddCommentsAboutDecision: 'Add comments about your decision...',
    drSelectAccountFromPayeer: 'Select account from Payeer Accounts...',
    drSelectExecutingBank: 'Select executing bank...',
    drSelectType: 'Select type...',
    drAdditionalNotesPlaceholder: 'Additional notes...',
  },

  id: {
    // Common
    loading: 'Memuat...',
    search: 'Cari',
    save: 'Simpan',
    cancel: 'Batal',
    close: 'Tutup',
    delete: 'Hapus',
    edit: 'Edit',
    view: 'Lihat',
    download: 'Unduh',
    upload: 'Unggah',
    uploading: 'Mengunggah...',
    submit: 'Kirim',
    back: 'Kembali',
    next: 'Berikutnya',
    previous: 'Sebelumnya',
    page: 'Halaman',
    of: 'dari',
    noDataFound: 'Data tidak ditemukan',
    tryAdjustingFilters: 'Coba sesuaikan filter Anda',

    // Dashboard
    clientDashboard: 'KLIEN',
    staffDashboard: 'STAF',
    manageYourFundTransfers: 'Kelola transfer dana Anda',
    manageOrdersClientsOperations: 'Kelola pesanan, klien, dan operasi',
    publicSite: 'Situs Publik',
    myProfile: 'Profil Saya',
    logout: 'Keluar',

    // Profile drawer
    profileTitle: 'Profil Saya',
    profileSubtitle: 'Informasi akun dan pengaturan',
    accountInformation: 'Informasi Akun',
    usernameLabel: 'Nama Pengguna',
    emailLabel: 'Email',
    roleLabel: 'Peran',
    changePassword: 'Ganti Kata Sandi',
    currentPassword: 'Kata Sandi Saat Ini',
    newPassword: 'Kata Sandi Baru',
    confirmNewPassword: 'Konfirmasi Kata Sandi Baru',
    enterCurrentPassword: 'Masukkan kata sandi saat ini',
    atLeast8Chars: 'Minimal 8 karakter',
    repeatNewPassword: 'Ulangi kata sandi baru',
    savePassword: 'Simpan Kata Sandi',
    saving: 'Menyimpan…',
    passwordChangedSuccess: 'Kata sandi berhasil diubah',
    passwordChangeFailed: 'Gagal mengubah kata sandi. Silakan coba lagi.',
    currentPasswordIncorrect: 'Kata sandi saat ini salah',
    enterCurrentPasswordError: 'Harap masukkan kata sandi saat ini',
    passwordMinLengthError: 'Kata sandi baru minimal 8 karakter',
    passwordsMismatch: 'Kata sandi tidak cocok',

    // Statistics
    totalOrders: 'Total Pesanan',
    currentOrders: 'Pesanan Saat Ini',
    executed: 'Selesai',
    cancelled: 'Dibatalkan',
    deleted: 'Dihapus',

    // Modules
    createOrder: 'Buat Pesanan',
    initiateFundTransfer: 'Mulai transfer dana baru',
    accountOnHold: 'Akun ditahan - hubungi dukungan',
    viewActiveOrders: 'Lihat pesanan aktif yang sedang diproses',
    viewCompletedOrders: 'Lihat pesanan yang selesai',
    viewCancelledOrders: 'Lihat pesanan yang dibatalkan',
    viewDeletedOrders: 'Lihat pesanan yang dihapus',
    executedOrders: 'Pesanan Selesai',
    cancelledOrders: 'Pesanan Dibatalkan',
    deletedOrders: 'Pesanan Dihapus',

    // Client Dashboard Sections
    history: 'Riwayat',
    requestsFromGTrans: 'Permintaan dari GTrans',
    otherRequests: 'Permintaan Lainnya',

    // Staff Dashboard
    administration: 'Administrasi',
    kyc: 'KYC',
    clients: 'Klien',
    manageClientAccounts: 'Kelola akun klien',
    activeOrders: 'Pesanan Aktif',
    viewProcessActiveOrders: 'Lihat dan proses pesanan aktif',
    payeerAccounts: 'Akun Payeer',
    managePayerAccounts: 'Kelola akun pembayar berdasarkan mata uang',
    kycDatabase: 'Database KYC',
    knowYourCustomer: 'Verifikasi Kenali Pelanggan Anda',
    kycOnboardingQueue: 'Antrean Onboarding KYC',
    reviewClientKYC: 'Tinjau pengajuan KYC klien',
    clientRequestsManagement: 'Manajemen Permintaan Klien',
    manageClientBadges: 'Kelola Lencana Klien',
    configureClientRequests: 'Konfigurasi permintaan yang terlihat oleh klien dan kelola status akun',

    // Orders Page
    searchOrders: 'Cari pesanan...',
    allStatuses: 'Semua Status',
    orderID: 'ID Pesanan',
    date: 'Tanggal',
    amount: 'Jumlah',
    beneficiary: 'Penerima',
    bank: 'Bank',
    status: 'Status',
    noOrdersFound: 'Tidak ada pesanan ditemukan',
    orders: 'pesanan',
    order: 'pesanan',

    // Order Actions
    viewTerms: 'Lihat Ketentuan',
    review: 'Tinjau',
    viewDetails: 'Lihat Detail',
    cancelSelected: 'Batalkan Yang Dipilih',
    deleteSelected: 'Hapus Yang Dipilih',
    terms: 'Ketentuan',

    // Status
    created: 'Dibuat',
    draft: 'Draf',
    check: 'Periksa',
    rejected: 'Ditolak',
    pending_payment: 'Menunggu Pembayaran',
    on_execution: 'Dalam Eksekusi',
    released: 'Dirilis',

    // Staff Actions
    createTxtInstruction: 'Buat Instruksi TXT',
    selected: 'dipilih',
    searchByOrderClient: 'Cari berdasarkan pesanan, klien, penerima, BIC...',
    filterByStatus: 'Filter berdasarkan status',
    currency: 'Mata Uang',
    all: 'Semua',
    clear: 'Hapus',
    client: 'Klien',
    invRcv: 'Inv Terima',
    proof: 'Bukti',
    nonM: 'Non-M',

    // Documents
    invoice: 'Faktur',
    paymentProof: 'Bukti Pembayaran',
    wordOrder: 'Pesanan WORD',
    submitted: 'Dikirim',
    uploadedBy: 'Diunggah oleh:',
    notUploadedYet: 'Belum diunggah',
    downloadCurrentVersion: 'Unduh Versi Saat Ini',
    downloadTemplate: 'Unduh Template',
    downloadDocument: 'Unduh Dokumen',
    reUpload: 'Unggah Ulang',
    staff: 'Staf',

    // Account Status
    accountOnHoldTitle: 'Akun Ditahan',
    accountOnHoldMessage: 'Akun Anda sementara ditahan. Silakan hubungi dukungan untuk informasi lebih lanjut.',

    // KYC
    kycVerification: 'Verifikasi KYC',
    kycStatus: 'Status',

    // Other Badges
    serviceAgreement: 'Perjanjian Layanan',

    // Additional Text
    searchDeletedOrders: 'Cari pesanan yang dihapus...',
    searchCancelledOrders: 'Cari pesanan yang dibatalkan...',
    searchClients: 'Cari klien...',
    dateCreated: 'Tanggal Dibuat',
    noDeletedOrders: 'Tidak ada pesanan yang dihapus',
    noCancelledOrders: 'Tidak ada pesanan yang dibatalkan',
    transactionStatus: 'Status Transaksi',
    settled: 'Diselesaikan',
    notSettled: 'Belum Diselesaikan',
    clientManagement: 'Manajemen Klien',
    clientID: 'ID Klien',
    name: 'Nama',
    signStatus: 'Status Tanda Tangan',
    accountStatus: 'Status Akun',
    signed: 'Ditandatangani',
    sent: 'Terkirim',
    notSent: 'Belum Terkirim',
    active: 'Aktif',
    inactive: 'Tidak Aktif',
    show: 'Tampilkan',
    kycReviewQueue: 'Antrean Tinjauan KYC',
    reviewProcessClientKYC: 'Tinjau dan proses pengajuan KYC klien',
    searchByCompanyOrClient: 'Cari berdasarkan nama perusahaan atau klien...',
    noKYCSubmissions: 'Tidak ada pengajuan KYC yang menunggu tinjauan',
    unknown: 'Tidak Diketahui',
    na: 'T/A',
    platformTerms: 'Syarat & Ketentuan Platform',
    sla: 'Perjanjian Tingkat Layanan (SLA)',
    dpa: 'Perjanjian Pemrosesan Data (DPA)',
    amlKycCompliance: 'Lampiran Kepatuhan AML/KYC',
    otherRequestSigning: 'Permintaan Penandatanganan Lainnya',
    otherRequestSubmit: 'Permintaan Pengiriman Lainnya',
    comingSoon: 'Segera Hadir',
    // Create Order Page
    createPaymentOrder: 'Buat Pesanan Pembayaran',
    dashboard: 'Dasbor',
    exportCSV: 'Ekspor CSV',
    invoiceRequired: 'Faktur Diperlukan',
    invoiceInstructions: 'Untuk menyelesaikan pemrosesan pesanan, kirimkan faktur Anda ke:',
    uploadDocumentsOptional: 'Unggah Dokumen (Opsional)',
    uploadHereOrEmail: 'Anda dapat mengunggah dokumen di sini atau mengirimkannya melalui email',
    uploadSalesContract: 'Unggah Kontrak Penjualan',
    uploadInvoice: 'Unggah Faktur',
    uploadOtherDocuments: 'Unggah Dokumen Lain',
    iAcceptThe: 'Saya menyetujui',
    termsAndConditions: 'Syarat & Ketentuan',
    byCheckingBoxAgree:
      'Dengan mencentang kotak ini, Anda setuju untuk mematuhi semua syarat, ketentuan, dan peraturan yang berlaku.',
    sendOrder: 'Kirim Pesanan',
    processing: 'Memproses...',
    openFullTermsPDF: 'Buka Syarat & Ketentuan Lengkap (PDF)',
    keyPoints: 'Poin Utama:',
    copy: 'Salin',
    trackYourTransfer: 'Lacak status transfer Anda',
    noActiveOrders2: 'Tidak ada pesanan aktif',
    tryClearing: 'Coba hapus pencarian Anda',
    searchOrdersOrBeneficiary: 'Cari pesanan atau penerima...',
    showingOf: 'Menampilkan',
    clickToViewFullDetails: 'Klik pesanan untuk melihat detail lengkap',
    rowsPerPageLabel: 'Baris per halaman:',
    pageOf: 'Halaman',
    noCancelledOrders2: 'Tidak ada pesanan yang dibatalkan',
    noDeletedOrders2: 'Tidak ada pesanan yang dihapus',
    // AmountCurrencySection
    paymentAmount: 'Jumlah Pembayaran',
    remittanceAmount: 'Jumlah Remitansi *',
    remittanceCurrency: 'Mata Uang Remitansi *',
    sourceCurrency: 'Mata Uang Sumber *',
    selectCurrency: 'Pilih mata uang',
    selectSourceCurrency: 'Pilih mata uang sumber',
    // BeneficiaryInfoSection
    beneficiaryInformation: 'Informasi Penerima',
    beneficiaryName: 'Nama Penerima *',
    beneficiaryNameHint: "(Maks 70 karakter, huruf Latin, angka, dan /-?:().,'+)",
    beneficiaryNamePlaceholder: 'Nama lengkap penerima',
    beneficiaryAddress: 'Alamat Penerima *',
    beneficiaryAddressHint: '(Maks 105 karakter, aturan sama seperti nama)',
    beneficiaryAddressPlaceholder: 'Alamat lengkap',
    beneficiaryCountry: 'Negara Penerima *',
    selectCountry: 'Pilih negara...',
    searchCountry: 'Cari negara...',
    noCountryFound: 'Negara tidak ditemukan.',
    characters: 'karakter',
    // BankDetailsSection
    bankDetails: 'Detail Bank',
    destinationAccount: 'Nomor Rekening Tujuan *',
    ibanRequired: '(Format IBAN diperlukan)',
    accountFormat: '(5-35 karakter, A-Z 0-9)',
    countryBank: 'Negara (Bank) *',
    bicLabel: 'BIC (Bank) *',
    bicChars: '(8 atau 11 karakter)',
    searchOrEnterBIC: 'Cari atau masukkan BIC...',
    searchBIC: 'Cari BIC...',
    noBICFound: 'BIC tidak ditemukan. Anda dapat memasukkan secara manual:',
    enterBICManually: 'Masukkan BIC secara manual',
    confirm: 'Konfirmasi',
    manualEntry: 'Masukkan manual',
    bankName: 'Nama Bank *',
    bankAddress: 'Alamat Bank *',
    bankNamePlaceholder: 'Nama bank',
    bankAddressPlaceholder: 'Alamat bank lengkap',
    manualOverrideWarning: '⚠️ Penggantian manual diaktifkan. Detail bank akan dicatat untuk ditinjau.',
    manualEntryNote: 'Entri manual - harap isi Nama Bank dan Alamat di bawah',
    // TransactionRemarkSection
    transactionRemark: 'Keterangan Transaksi',
    templateMode: 'Template',
    manualMode: 'Manual',
    transactionRemarkLabel: 'Keterangan Transaksi *',
    transactionRemarkChars: '(Maks 500 karakter)',
    enterTransactionRemark: 'Masukkan keterangan transaksi...',
    templateLabel: 'Template:',
    paymentType: 'Jenis Pembayaran',
    goods: 'Barang',
    documents: 'Dokumen',
    addDocument: 'Tambah Dokumen',
    documentType: 'Jenis Dokumen *',
    documentNumber: 'Nomor Dokumen *',
    documentDate: 'Tanggal Dokumen *',
    preview: 'Pratinjau:',
    fillFieldsPreview: 'Isi kolom yang diperlukan untuk melihat pratinjau...',
    paymentPlaceholder: 'Pembayaran, pembayaran sebagian',
    goodsPlaceholder: 'barang',
    characters500: '500 karakter',
    // Common table/UI
    orderId: 'ID Pesanan',
    amountLabel: 'Jumlah',
    beneficiaryLabel: 'Penerima',
    bankLabel: 'Bank',
    clientLabel: 'Klien',
    ofLabel: 'dari',
    loadingDots: 'Memuat...',
    loadingYourOrders: 'Memuat pesanan Anda...',
    searchOrdersPlaceholder: 'Cari pesanan...',
    searchOrdersBeneficiary: 'Cari pesanan atau penerima...',
    searchCancelledPlaceholder: 'Cari pesanan yang dibatalkan...',
    searchDeletedPlaceholder: 'Cari pesanan yang dihapus...',
    newestFirst: 'Terbaru dulu',
    oldestFirst: 'Terlama dulu',
    noActiveOrders: 'Tidak ada pesanan aktif',
    noExecutedOrders: 'Tidak ada pesanan yang dieksekusi',
    tryClearingSearch: 'Coba hapus pencarian Anda',
    noneLabel: 'Tidak ada',
    allOrders: 'Semua Pesanan',
    byClient: 'Per Klien',
    byStatus: 'Per Status',
    filterBySettled: 'Filter berdasarkan penyelesaian',
    settledLabel: 'Sudah Selesai',
    notSettledLabel: 'Belum Selesai',
    naLabel: 'N/A',
    txStatus: 'Status Tx',
    actReport: 'Laporan Akta',
    salesContract: 'Kontrak Penjualan',
    invoiceLabel: 'Faktur',
    otherDocuments: 'Dokumen Lainnya',
    clickToViewDetails: 'Klik pesanan mana pun untuk melihat detail lengkap',
    trackTransferStatus: 'Lacak status transfer Anda',
    avgLabel: 'rata-rata',
    clearFilters: 'Hapus',
    orderLabel: 'pesanan',
    ordersLabel: 'pesanan',
    showing: 'Menampilkan',
    txStatusHeader: 'Status Transaksi',
    selectOnExecution: 'Pilih Yang Sedang Dieksekusi',
    selectedLabel: 'dipilih',
    createTxt: 'Buat TXT',
    markExecuted: 'Tandai Selesai',
    deleteLabel: 'Hapus',
    noOrdersLabel: 'Tidak ada pesanan',
    searchActiveOrdersPlaceholder: 'Cari berdasarkan pesanan, klien, penerima, BIC...',
    invNum: 'No Fakt',
    allCurrencies: 'Semua Mata Uang',
    // StaffActiveOrders dialogs
    unusualTransactionTitle: 'Transaksi Tidak Biasa Terdeteksi',
    unusualTransactionDesc: 'jauh di atas rata-rata historis mereka.',
    thisOrder: 'Pesanan ini:',
    clientAvgLabel: 'Rata-rata klien:',
    deviationLabel: 'Deviasi:',
    xAboveAverage: 'x di atas rata-rata',
    enhancedVerification: 'Harap lakukan tinjauan menyeluruh. Verifikasi yang ditingkatkan mungkin diperlukan.',
    proceedToReview: 'Lanjut ke Tinjauan',
    cancelLabel: 'Batal',
    deleteOrdersTitle: 'Pesanan',
    deleteOrdersDesc: 'Apakah Anda yakin ingin menghapus pesanan yang dipilih? Tindakan ini tidak dapat dibatalkan.',
    clientOrdersBadge: 'pesanan',
    // StaffExecutedOrders
    executedOrdersTitle: 'Pesanan Selesai',
    // StaffDashboard
    staffLabel: 'STAF',
    staffSubtitle: 'Kelola pesanan, klien, dan operasional',
    administrationSection: 'Administrasi',
    ordersSection: 'Pesanan',
    kycSection: 'KYC',
    reportsSection: 'Laporan',
    requestsSection: 'Permintaan',
    mod_clients_title: 'Klien',
    mod_clients_desc: 'Kelola akun klien',
    mod_activeOrders_title: 'Pesanan Aktif',
    mod_activeOrders_desc: 'Lihat dan proses pesanan aktif',
    mod_executedOrders_title: 'Pesanan Selesai',
    mod_executedOrders_desc: 'Lihat pesanan yang telah selesai',
    mod_payeerAccounts_title: 'Akun Payeer',
    mod_payeerAccounts_desc: 'Kelola akun pembayar berdasarkan mata uang',
    mod_kycDatabase_title: 'Database KYC',
    mod_kycDatabase_desc: 'Database verifikasi Kenali Pelanggan Anda',
    mod_kycQueue_title: 'Antrian Onboarding KYC',
    mod_kycQueue_desc: 'Tinjau pengajuan KYC klien',
    mod_transactionData_title: 'Data Transaksi',
    mod_transactionData_desc: 'Database transaksi lengkap dengan sortir, filter & ekspor Excel',
    mod_customerData_title: 'Data Pelanggan',
    mod_customerData_desc: 'Data klien & rekanan dengan field KYC & ekspor Excel',
    mod_manageBadges_title: 'Kelola Badge',
    mod_manageBadges_desc: 'Status akun, KYC, dan badge Perjanjian Layanan',
    mod_serviceAgreement_title: 'Perjanjian Layanan',
    mod_serviceAgreement_desc: 'Kelola dokumen utama dan pengajuan klien',
    // StaffClients
    clientManagementTitle: 'Manajemen Klien',
    clientsCountLabel: 'klien',
    addClient: 'Tambah Klien',
    searchClientsPlaceholder: 'Cari klien...',
    clientIdColumn: 'ID Klien',
    nameColumn: 'Nama',
    signStatusColumn: 'Status Tanda Tangan',
    accountStatusColumn: 'Status Akun',
    activeStatus: 'Aktif',
    inactiveStatus: 'Tidak Aktif',
    signedStatus: 'Ditandatangani',
    sentStatus: 'Terkirim',
    notSentStatus: 'Belum Dikirim',
    showLabel: 'Tampilkan:',
    noClientsFound: 'Tidak ada klien ditemukan',
    editClientTitle: 'Edit Klien',
    addNewClientTitle: 'Tambah Klien Baru',
    clientInfoSection: 'Informasi Klien',
    docSigningSection: 'Dokumen & Penandatanganan',
    groupReferenceSection: 'Grup & Referensi',
    authCredentialsSection: 'Kredensial Otorisasi',
    generatePassword: 'Buat Kata Sandi',
    saveClient: 'Simpan Klien',
    savingLabel: 'Menyimpan...',
    deleteClientTitle: 'Hapus Klien',
    deleteClientDesc: 'Apakah Anda yakin ingin menghapus klien ini? Tindakan ini tidak dapat dibatalkan.',
    activeLabel: 'Aktif',
    // StaffKYCQueue
    backToDashboard: 'Kembali ke Dashboard',
    kycReviewQueueTitle: 'Antrian Tinjauan KYC',
    kycReviewQueueSubtitle: 'Tinjau dan proses pengajuan KYC klien',
    searchKYCPlaceholder: 'Cari berdasarkan nama perusahaan atau klien...',
    noKYCPending: 'Tidak ada pengajuan KYC yang menunggu tinjauan',
    companyNameNotProvided: 'Nama Perusahaan Belum Diberikan',
    submittedAtLabel: 'Dikirim:',
    reviewButton: 'Tinjau',
    unknownLabel: 'Tidak Diketahui',
    // StaffClients form fields
    fieldClientIdLabel: 'ID Klien *',
    fieldClientNameLabel: 'Nama Klien *',
    fieldAlias1: 'Alias 1',
    fieldAlias2: 'Alias 2',
    fieldAlias3: 'Alias 3',
    fieldRegNumber: 'Nomor Registrasi (contoh NIB)',
    fieldTaxNumber: 'Nomor Pajak (contoh NPWP)',
    fieldRegCountry: 'Negara Registrasi',
    fieldDirectorName: 'Nama Direktur',
    fieldEmail: 'Email *',
    fieldDocId: 'ID Dokumen',
    fieldSigningStatus: 'Status Penandatanganan',
    fieldDateSigning: 'Tanggal Penandatanganan',
    fieldGroupId: 'ID Grup',
    fieldGroupName: 'Nama Grup',
    fieldLastId: 'ID Terakhir',
    fieldLogin: 'Login *',
    fieldPassword: 'Kata Sandi *',
    fieldDescription: 'Deskripsi',
    phClientId: 'contoh, CL1',
    phClientName: 'Nama klien',
    phAltName1: 'Nama alternatif 1',
    phAltName2: 'Nama alternatif 2',
    phAltName3: 'Nama alternatif 3',
    phRegNumber: 'contoh 1234567890123456789',
    phTaxNumber: 'contoh 12.345.678.9-012.345',
    phCountry: 'Negara',
    phDirectorName: 'Nama direktur',
    phEmail: 'klien@example.com',
    phDocId: 'contoh, AGG/1/20261201',
    phGroupId: 'contoh, 1',
    phGroupName: 'contoh, Grup1',
    phLastRef: 'Referensi terakhir',
    phUsername: 'namapengguna',
    phAdditionalNotes: 'Catatan tambahan',
    optNotSent: 'Belum Dikirim',
    optSent: 'Terkirim',
    optSigned: 'Ditandatangani',
    pageOfLabel: 'dari',
    // StaffTransactionReport
    transactionDataReport: 'Laporan Data Transaksi',
    searchTransactionPlaceholder: 'Cari ID, pengirim, penerima, mata uang…',
    allTypes: 'Semua Jenis',
    ingoing: 'Masuk',
    outgoing: 'Keluar',
    domestic: 'Domestik',
    allRisk: 'Semua Risiko',
    riskLow: 'Rendah',
    riskMedium: 'Sedang',
    riskHigh: 'Tinggi',
    downloadExcel: 'Unduh Excel',
    addRecord: 'Tambah Rekod',
    addCustomer: 'Tambah Pelanggan',
    actionsLabel: 'Aksi',
    rowsPerPage: 'Baris per halaman:',
    pageLabel: 'Halaman',
    prevLabel: 'Sebelum',
    nextLabel: 'Berikut',
    noRecordsFound: 'Tidak ada rekod ditemukan',
    // StaffCustomerReport
    customerDataReport: 'Laporan Data Pelanggan',
    searchCustomerPlaceholder: 'Cari berdasarkan nama, nomor pajak, direktur…',
    allCustomerTypes: 'Semua Jenis',
    allCodes: 'Semua Kode',
    pepAll: 'PEP: Semua',
    pepYes: 'PEP: Ya',
    pepNo: 'PEP: Tidak',
    citizenshipAll: 'Kewarganegaraan: Semua',
    indonesianYes: 'WNI: Ya',
    indonesianNo: 'WNI: Tidak',
    // ClientKYC
    backToDashboardBtn: 'Kembali ke Dashboard',
    kycVerificationTitle: 'Verifikasi KYC',
    kycVerificationDesc: 'Lengkapi verifikasi Know Your Customer Anda',
    kycStatusNotStarted: 'Belum Dimulai',
    kycStatusInProgress: 'Sedang Berjalan',
    kycStatusUnderReview: 'Dalam Tinjauan',
    kycStatusApproved: 'Disetujui',
    kycStatusRejected: 'Ditolak',
    kycStepCorporate: 'Detail Perusahaan',
    kycStepDocuments: 'Dokumen',
    kycStepBanking: 'Detail Perbankan',
    kycStepOwnership: 'Kepemilikan',
    kycStepDeclaration: 'Deklarasi & Tanda Tangan',
    previousBtn: 'Sebelumnya',
    saveProgressBtn: 'Simpan Progres',
    nextBtn: 'Selanjutnya',
    submitKYCBtn: 'Kirim KYC',
    riskAlert: 'Peringatan Risiko',

    // ===== Client i18n batch =====
    // Validation (CreateOrder)
    valAmountRequired: 'Jumlah wajib diisi',
    valCurrencyRequired: 'Mata uang wajib diisi',
    valBeneficiaryCountryRequired: 'Negara penerima wajib diisi',
    valAccountNumberRequired: 'Nomor rekening wajib diisi',
    valBankCountryRequired: 'Negara wajib diisi',
    valBicRequired: 'BIC wajib diisi',
    valBankNameRequired: 'Nama bank wajib diisi',
    valBankAddressRequired: 'Alamat bank wajib diisi',
    valTransactionRemarkRequired: 'Keterangan transaksi wajib diisi',
    valEnableManualOverride: 'Aktifkan penggantian manual untuk mengisi detail bank',
    valTermsRequired: 'Harap setujui Syarat & Ketentuan untuk melanjutkan',
    valFixErrorsBeforeSubmit: 'Harap perbaiki semua kesalahan sebelum mengirim',
    valTransactionRemarkExceeds500: 'Keterangan transaksi melebihi 500 karakter',
    valAddAtLeastOneDocument: 'Harap tambahkan setidaknya satu dokumen',
    // CreateOrder toasts
    orderCreatedSuccess: 'Pesanan berhasil dibuat!',
    failedCreateOrder: 'Gagal membuat pesanan',
    emailCopiedToClipboard: 'Email disalin ke clipboard',
    subjectCopiedToClipboard: 'Subjek disalin ke clipboard',
    documentSelected: 'Dokumen dipilih',
    uploadedSuccessfully: 'berhasil diunggah',
    failedUploadSomeDocuments: 'Gagal mengunggah beberapa dokumen',
    couldNotOpenTerms: 'Tidak dapat membuka Syarat & Ketentuan',
    failedLoadTerms: 'Gagal memuat Syarat & Ketentuan',
    // Terms paragraphs
    termsKeyPoint1: 'Semua transfer dana mematuhi peraturan Indonesia termasuk undang-undang Anti Pencucian Uang',
    termsKeyPoint2:
      'PT GARUDA ARMA NUSA akan melaksanakan transfer sesuai dengan Perintah Transfer Dana yang ditandatangani',
    termsKeyPoint3: 'Pesanan harus dikirimkan setidaknya 1 jam sebelum waktu cut-off mata uang',
    termsKeyPoint4: 'Pembayaran harus diterima 30 menit sebelum waktu cut-off',
    termsKeyPoint5: 'Pesanan hanya berlaku sekali pada tanggal yang dinyatakan',
    termsKeyPoint6: 'Penandatangan resmi harus didokumentasikan sesuai Formulir Data Pelanggan',
    termsRegulationsApplied: 'Peraturan yang Berlaku:',
    termsRegulation1: 'UU No. 8/2010 - Pencegahan dan Pemberantasan Tindak Pidana Pencucian Uang',
    termsRegulation2: 'UU No. 3/2011 - Transfer Dana',
    termsRegulation3: 'UU No. 9/2013 - Pencegahan Pendanaan Terorisme',
    termsRegulation4: 'UU No. 27/2022 - Perlindungan Data Pribadi',
    termsRegulation5: 'Peraturan Bank Indonesia tentang Layanan Pembayaran',
    // Page titles / subtitles
    orderHistorySubtitle: 'Riwayat Pesanan',
    saSubtitle: 'Perjanjian Layanan',
    submitNdaSubtitle: 'Kirim Dokumen NDA',
    // OrderHistory
    loadingOrdersText: 'Memuat pesanan...',
    noOrdersYetTitle: 'Belum ada pesanan',
    createFirstOrderHint: 'Buat pesanan remitansi pertama Anda untuk memulai.',
    noOrdersMatchFilter: 'Tidak ada pesanan yang cocok dengan filter saat ini.',
    pageOfText: 'Halaman',
    ordersFoundText: 'ditemukan',
    // OrderFilters
    filtersLabel: 'Filter',
    filterSearchByOrderBeneficiaryBic: 'Cari berdasarkan ID Pesanan, Penerima, BIC...',
    statusPlaceholder: 'Status',
    currencyPlaceholder: 'Mata Uang',
    fromDatePlaceholder: 'Dari tanggal',
    toDatePlaceholder: 'Sampai tanggal',
    clearFiltersBtnLabel: 'Hapus filter',
    // Status labels (badges)
    statusUnderReviewLabel: 'Sedang Ditinjau',
    statusInProgressLabel: 'Sedang Berlangsung',
    statusCanceledLabel: 'Dibatalkan',
    statusClientCanceledLabel: 'Dibatalkan Klien',
    statusCreatedDesc: 'Pesanan diajukan, menunggu tinjauan',
    statusUnderReviewDesc: 'Tim kami sedang meninjau pesanan Anda',
    statusPendingPaymentDesc: 'Menunggu pembayaran Anda',
    statusInProgressDesc: 'Transfer sedang diproses',
    // OrderDetailsDrawer
    statusTimeline: 'Linimasa Status',
    csvDownloadedToast: 'CSV diunduh',
    orderIdCopiedToast: 'ID Pesanan disalin',
    paymentDetails: 'Detail Pembayaran',
    drawerBeneficiarySection: 'Penerima',
    detailNameLabel: 'Nama',
    detailAddressLabel: 'Alamat',
    detailAccountLabel: 'Rekening',
    detailBankNameLabel: 'Nama Bank',
    detailBicSwiftLabel: 'BIC/SWIFT',
    detailCountryLabel: 'Negara',
    downloadCsvBtn: 'Unduh CSV',
    // ClientNDA
    ndaInformationSavedToast: 'Informasi NDA disimpan',
    ndaSubmittedForReviewToast: 'NDA dikirim untuk ditinjau!',
    saveNdaFirst: 'Harap simpan informasi NDA terlebih dahulu',
    failedUploadFile: 'Gagal mengunggah file',
    signedNdaUploadedToast: 'NDA bertanda tangan diunggah',
    ndaRequestTitle: 'Permintaan NDA',
    ndaRequestSubtitle: 'Kirimkan informasi Perjanjian Kerahasiaan Anda',
    partnerInformation: 'Informasi Mitra',
    effectiveDateLabel: 'Tanggal Berlaku *',
    partnerInnLabel: 'INN Mitra',
    partnerNameRu: 'Nama Mitra (Rusia) *',
    partnerNameEn: 'Nama Mitra (Inggris) *',
    partnerAddressRu: 'Alamat Mitra (Rusia)',
    partnerAddressEn: 'Alamat Mitra (Inggris)',
    contactNameLabel: 'Nama Kontak',
    contactEmailLabel: 'Email Kontak',
    contactPhoneLabel: 'Telepon Kontak',
    paperCopyRequired: 'Salinan kertas diperlukan',
    generatedNdaTitle: 'NDA yang Dibuat',
    downloadGeneratedNda: 'Unduh NDA yang Dibuat',
    uploadSignedNdaTitle: 'Unggah NDA Bertanda Tangan',
    uploadSignedNdaBtnLabel: 'Unggah NDA Bertanda Tangan',
    viewUploadedNda: 'Lihat NDA yang Diunggah',
    saveProgressLabel: 'Simpan Progres',
    submitNdaLabel: 'Kirim NDA',
    errorLoadingClient: 'Kesalahan memuat data klien',
    // ClientSubmitNDA
    ndaDocumentSubmissionTitle: 'Pengajuan Dokumen NDA',
    pleaseDownloadSignAndUpload: 'Harap unduh, tanda tangani, dan unggah dokumen NDA.',
    ndaTemplateLabel: 'Template NDA',
    downloadSignAndUploadHint: 'Unduh dokumen ini, tanda tangani, dan unggah di bawah',
    documentSubmittedTitle: 'Dokumen Dikirim',
    ndaUnderReviewMsg: 'NDA Anda telah dikirim dan sedang ditinjau',
    viewSubmittedDocumentBtn: 'Lihat Dokumen yang Dikirim',
    uploadSignedNdaPdfHelp: 'Unggah dokumen NDA yang ditandatangani (format PDF)',
    selectFileBtn: 'Pilih Berkas',
    statusColon: 'Status:',
    ndaUploadFailedToast: 'Pengunggahan gagal',
    ndaUploadSuccessToast: 'NDA berhasil dikirim',
    // ClientServiceAgreement
    signedSaUploadSuccessToast: 'Perjanjian Layanan bertanda tangan berhasil diunggah',
    failedToUploadDocumentToast: 'Gagal mengunggah dokumen',
    saGeneratedSuccessToast: 'Perjanjian Layanan berhasil dibuat',
    failedGenerateSaToast: 'Gagal membuat Perjanjian Layanan',
    agreementAcceptedTitle: 'Perjanjian Diterima',
    saAcceptedDesc: 'Perjanjian Layanan Anda telah ditinjau dan diterima oleh GTrans.',
    underReviewTitle: 'Sedang Ditinjau',
    saUnderReviewDesc: 'Perjanjian Layanan bertanda tangan Anda sedang ditinjau oleh tim kami.',
    instructionsTitle: 'Petunjuk',
    saInstructionsDesc: 'Ikuti langkah-langkah ini untuk menyelesaikan Perjanjian Layanan',
    step1Heading: 'Unduh Perjanjian',
    step1Desc: 'Klik tombol unduh di bawah untuk mendapatkan dokumen Perjanjian Layanan.',
    step2Heading: 'Tinjau dan Tanda Tangani',
    step2Desc: 'Baca perjanjian dengan cermat dan tanda tangani dengan penandatangan resmi.',
    step3Heading: 'Unggah Salinan Bertanda Tangan',
    step3Desc: 'Unggah perjanjian yang ditandatangani menggunakan tombol unggah di bawah.',
    step1DownloadTitle: 'Langkah 1: Unduh Perjanjian',
    step2UploadTitle: 'Langkah 2: Unggah Perjanjian Bertanda Tangan',
    saDocxDocument: 'Dokumen DOCX',
    noteFromGtrans: 'Catatan dari GTrans:',
    alternativeStaffDoc: 'Dokumen alternatif yang disediakan oleh staf:',
    downloadStaffDocument: 'Unduh Dokumen Staf',
    signedAgreementUploaded: 'Perjanjian Bertanda Tangan Diunggah',
    yourSignedDocSubmitted: 'Dokumen bertanda tangan Anda telah dikirim',
    viewLabelBtn: 'Lihat',
    replaceLabelBtn: 'Ganti',
    uploadSignedAgreementBtn: 'Unggah Perjanjian Bertanda Tangan',
    generatingDots: 'Membuat...',
    acceptedFormatsHint: 'Format yang diterima: PDF, DOC, DOCX',
    saHeaderSubtitle: 'Unduh, tanda tangani, dan unggah perjanjian',
    // KYC Corporate Details
    kycCompanyNameLabel: 'Nama Perusahaan *',
    kycTradingNameLabel: 'Nama Dagang',
    kycIncorporationDateLabel: 'Tanggal Pendirian',
    kycIncorporationCountryLabel: 'Negara Pendirian',
    kycRegisteredAddressLabel: 'Alamat Terdaftar *',
    kycTaxIdLabel: 'NPWP',
    kycRegistrationNumberLabel: 'Nomor Registrasi',
    kycTelephoneLabel: 'Telepon',
    kycWebsiteLabel: 'Situs Web',
    // KYC Documents
    kycSectionCompanyId: '2. Detail Identifikasi Perusahaan',
    kycDocumentsInstruction:
      'Harap sediakan salinan dokumen di bawah ini. Dokumen-dokumen ini harus disediakan dalam Bahasa Inggris atau dengan Terjemahan Bahasa Inggris.',
    kycMandatoryDocsHeader: 'Dokumen wajib yang harus disediakan',
    kycUploadHeader: 'Unggah',
    kycDocCertOfIncorporation: 'Sertifikat Pendirian',
    kycDocTradeLicense: 'Izin Usaha',
    kycDocCommitteeList: 'Daftar Komite Perusahaan (Komisaris & Direktur)',
    kycDocMemorandum: 'Anggaran Dasar dan Perubahannya',
    kycDocShareholdersList: 'Daftar Pemegang Saham dan Modal',
    kycDocAuthSignatories: 'Daftar Penandatangan Resmi dengan Autentikasi Tanda Tangan',
    kycDocPassportSignatories: 'Salinan Paspor untuk Penandatangan Resmi (2.6)',
    kycUploadedLabel: 'Terunggah',
    kycDownloadFailed: 'Gagal mengunduh',
    kycFileUploadedSuccess: 'File berhasil diunggah',
    kycFailedUploadFile: 'Gagal mengunggah file',
    // KYC Banking
    kycBankingTitle: '3. Detail Perbankan',
    kycBankingInstruction: 'Harap sediakan detail perbankan lengkap',
    kycPrincipalBankers: 'Bank Utama (Nama Bank)',
    kycSwiftBicLabel: 'Swift BIC',
    kycBankBranchAddress: 'Detail Alamat Cabang Bank',
    kycBankCityCountry: 'Kota & Negara Bank',
    kycBankAccountName: 'Nama Rekening Bank',
    kycBankAccountCurrency: 'Mata Uang Rekening Bank',
    kycBankAccountNumber: 'Nomor Rekening Bank/Nomor IBAN',
    kycBankManagerContact: 'Nama Manajer Rekening Bank & Detail Kontak',
    // KYC Ownership
    kycOwnershipTitle: '4. Informasi Kepemilikan',
    kycAddShareholder: 'Tambah Pemegang Saham',
    kycShareholderAddedToast: 'Pemegang saham ditambahkan',
    kycShareholderRemovedToast: 'Pemegang saham dihapus',
    kycClientIdMissingToast: 'ID Klien hilang',
    kycFailedToUpdateToast: 'Gagal memperbarui',
    kycNoShareholdersYet: 'Belum ada pemegang saham. Klik "Tambah Pemegang Saham" untuk memulai.',
    kycShareholderLabel: 'Pemegang Saham',
    kycShareholderNameLabel: 'Nama Pemegang Saham dan UBO (Sesuai Paspor atau Dokumen Izin)',
    kycShareholderNamePlaceholder: 'Masukkan nama pemegang saham',
    kycShareholdingLabel: 'Persentase Kepemilikan %',
    kycNationalityResidence: 'Kewarganegaraan dan Negara Tempat Tinggal',
    kycNationalityPlaceholder: 'Kewarganegaraan',
    // KYC Declaration
    kycDeclarationSection: '5. Deklarasi',
    kycDeclarationText:
      'Dengan ini dinyatakan bahwa informasi dan perincian yang diberikan di atas adalah benar dan akurat sebaik pengetahuan dan keyakinan saya/kami dan bahwa tidak ada yang disalahartikan dan/atau disembunyikan.',
    kycDeclarationConfirm: 'Saya mengonfirmasi bahwa saya telah membaca dan menyetujui deklarasi di atas *',
    kycSignatureSection: '6. Tanda Tangan',
    kycAuthorizedPersonName: 'Nama orang yang berwenang mengisi Formulir Pendaftaran ini *',
    kycDateColon: 'Tanggal:',
    kycPositionLabel: 'Posisi',
    kycLocationColon: 'Lokasi:',
    kycPowerOfAttorneyNote:
      'Jika Formulir Pendaftaran diisi oleh orang yang tidak berwenang, harap sediakan Surat Kuasa',
    kycDownloadUploadHeader: 'Unduh & Unggah Dokumen Bertanda Tangan',
    kycDownloadKycForm: 'Unduh Formulir KYC (dengan data terisi)',
    kycUploadSignedKycDoc: 'Unggah Dokumen KYC yang Ditandatangani',
    kycDocumentUploadedLabel: 'Dokumen Terunggah',
    kycReplaceLabel: 'Ganti',
    kycUploadSignedDocBtn: 'Unggah Dokumen yang Ditandatangani',
    kycSavingGenerating: 'Menyimpan & Membuat Dokumen...',
    kycDocumentDownloaded: 'Dokumen KYC diunduh',
    kycFailedDownload: 'Gagal mengunduh dokumen KYC',
    kycSignedDocUploadHelp: 'Harap unduh formulir di atas, tanda tangani, dan unggah pindaian PDF.',
    kycClientIdMissingError: 'ID Klien hilang',
    // Remittance: BeneficiarySection
    beneficiaryDetailsTitle: 'Detail Penerima',
    recipientNameLabel: 'Nama Penerima *',
    recipientNamePlaceholder: 'Nama lengkap penerima',
    beneficiaryAddressLabel: 'Alamat Penerima',
    beneficiaryAddressFullPlaceholder: 'Alamat lengkap',
    beneficiaryCountryLabel: 'Negara',
    beneficiaryCountryPlaceholder: 'Negara penerima',
    registrationNumberLabel: 'Nomor Registrasi',
    registrationNumberPlaceholder: 'NPWP atau nomor registrasi',
    accountNumberIbanLabel: 'Nomor Rekening / IBAN',
    accountNumberIbanPlaceholder: 'Nomor rekening bank atau IBAN',
    beneficiaryBankLabel: 'Bank Penerima',
    beneficiaryBankPlaceholder: 'Nama bank',
    bicSwiftCodeLabel: 'Kode BIC/SWIFT',
    bicIdentifierCodePlaceholder: 'Kode Identifikasi Bank',
    bankAddressFieldLabel: 'Alamat Bank',
    bankAddressFullPlaceholder: 'Alamat bank lengkap',
    // BankDetailsSection
    accountNumberPlainPlaceholder: 'Nomor rekening',
    // TransactionRemarkSection
    docNumberExamplePlaceholder: 'contoh, 24543',
    // InvoiceInfoModal
    orderCreatedSuccessTitle: 'Pesanan Berhasil Dibuat!',
    sendYourInvoiceTitle: 'Kirim Faktur Anda',
    sendInvoiceInstruction: 'Untuk menyelesaikan pemrosesan pesanan, kirimkan faktur Anda ke:',
    emailAddressColon: 'Alamat Email:',
    emailSubjectColon: 'Subjek Email:',
    orderInDraftMessage:
      'Pesanan Anda saat ini berstatus Draf. Pesanan akan diproses setelah kami menerima faktur Anda.',
    gotItButton: 'Mengerti',
    // ClientTermsDrawer
    termsSectionLabel: 'Ketentuan',
    drawerAmountLabel: 'Jumlah',
    remunerationTypeLabel: 'Jenis Imbalan',
    remunerationPercentLabel: 'Imbalan %',
    remunerationFixedLabel: 'Imbalan Tetap',
    amountRemunerationLabel: 'Jumlah Imbalan',
    clientPaymentCurrencyLabel: 'Mata Uang Pembayaran Klien',
    exchangeRateLabel: 'Nilai Tukar',
    fvLabel: 'FV',
    remunerationLabel: 'Imbalan',
    totalUppercaseLabel: 'TOTAL',
    uploadPaymentProofLabel: 'Unggah Bukti Pembayaran',
    uploadPaymentProofBtn: 'Unggah Bukti Pembayaran',
    uploadingDots: 'Mengunggah...',
    uploadingShort: 'Mengunggah..',
    uploadedColon: 'Diunggah:',
    dataFixingLabel: 'Penetapan Data',
    datePaidLabel: 'Tanggal Dibayar',
    notPaidLabel: 'Belum Dibayar',
    orderDocumentSection: 'Dokumen Pesanan',
    orderFromStaffLabel: 'Pesanan (dari Staf)',
    downloadUnsignedOrderBtn: 'Unduh Pesanan Belum Ditandatangani',
    noOrderDocAvailable: 'Belum ada dokumen pesanan tersedia',
    uploadSignedOrderLabel: 'Unggah Pesanan Bertanda Tangan',
    uploadSignedOrderBtn: 'Unggah Pesanan Bertanda Tangan',
    signedOrderFromStaffLabel: 'Pesanan Bertanda Tangan (dari Staf)',
    downloadSignedOrderBtn: 'Unduh Pesanan Bertanda Tangan',
    orderInformationSection: 'Informasi Pesanan',
    beneficiaryNameColon: 'Nama Penerima:',
    beneficiaryAddressColon: 'Alamat Penerima:',
    destinationAccountColon: 'Rekening Tujuan:',
    bankNameColon: 'Nama Bank:',
    bicSwiftColon: 'BIC/SWIFT:',
    bankAddressColon: 'Alamat Bank:',
    countryColon: 'Negara:',
    remarkColon: 'Keterangan:',
    payeerAccountInformation: 'Informasi Akun Payeer',
    accountNameLabel: 'Nama Akun',
    accountNumberDrawerLabel: 'Nomor Akun',
    drawerCurrencyLabel: 'Mata Uang',
    bicLabelShort: 'BIC:',
    swiftLabelShort: 'SWIFT:',
    payeerIdLabel: 'ID Payeer:',
    cancelOrderBtn: 'Batalkan Pesanan',
    closeBtn: 'Tutup',
    cancelOrderTitle: 'Batalkan Pesanan?',
    cancelOrderDesc: 'Tindakan ini akan menandai pesanan sebagai dibatalkan. Tindakan ini dapat dibatalkan oleh staf.',
    noKeepIt: 'Tidak, Pertahankan',
    yesCancelOrder: 'Ya, Batalkan Pesanan',
    deleteOrderTitle: 'Hapus Pesanan?',
    deleteOrderDesc:
      'Tindakan ini akan menandai pesanan sebagai dihapus. Hanya pesanan yang ditolak yang dapat dihapus.',
    yesDeleteOrder: 'Ya, Hapus Pesanan',
    toastOrderCancelled: 'Pesanan dibatalkan',
    toastFailedCancelOrder: 'Gagal membatalkan pesanan',
    toastOrderDeleted: 'Pesanan dihapus',
    toastFailedDeleteOrder: 'Gagal menghapus pesanan',
    toastSignedOrderUploaded: 'Pesanan bertanda tangan berhasil diunggah',
    toastFailedUploadSignedOrder: 'Gagal mengunggah pesanan bertanda tangan',
    toastPaymentProofUploaded: 'Bukti pembayaran berhasil diunggah',
    toastFailedUploadPaymentProof: 'Gagal mengunggah bukti pembayaran',
    toastFailedDownloadDoc: 'Gagal mengunduh dokumen',
    toastExcelDownloaded: 'Excel berhasil diunduh',
    toastFailedDownloadExcel: 'Gagal mengunduh Excel',
    // ClientExecutedDrawer
    executedDetailsSubtitle: 'Detail untuk pesanan yang dieksekusi',
    transactionStatusUppercase: 'Status Transaksi',
    statusReceivedLabel: 'Diterima',
    statusNotReceivedLabel: 'Belum Diterima',
    drawerNumberLabel: 'Nomor',
    drawerDateLabel: 'Tanggal',
    downloadTransactionStatusBtn: 'Unduh Status Transaksi',
    mt103Title: 'MT103',
    downloadMt103Btn: 'Unduh MT103',
    actReportTitle: 'Laporan Akta',
    actSignedLabel: 'Ditandatangani',
    actOnSignLabel: 'Sedang Ditandatangani',
    actNotMadeLabel: 'Belum Dibuat',
    downloadActReportBtn: 'Unduh Laporan Akta',
    downloadUnsignedActReportBtn: 'Unduh Laporan Akta Belum Ditandatangani',
    uploadSignedActReportLabel: 'Unggah Laporan Akta Bertanda Tangan',
    uploadSignedActReportBtn: 'Unggah Laporan Akta Bertanda Tangan',
    failedUploadActReportToast: 'Gagal mengunggah Laporan Akta',
    signedActReportUploadedToast: 'Laporan Akta bertanda tangan berhasil diunggah',
    failedDownloadUrlToast: 'Gagal mendapatkan URL unduh',
    documentsHeader: 'Dokumen',
    salesContractDrawerLabel: 'Kontrak Penjualan',
    invoiceDrawerLabel: 'Faktur',
    otherDocumentsDrawerLabel: 'Dokumen Lainnya',
    wordOrderDrawerLabel: 'Pesanan WORD',
    signedWordOrderDrawerLabel: 'Pesanan WORD Bertanda Tangan',
    downloadShortLabel: 'Unduh',
    remittanceCurrencyLabel: 'Mata Uang Remitansi',
    debitAccountLabel: 'Rekening Debit',
    transactionReferenceLabel: 'Referensi Transaksi',
    bankCountryLabel: 'Negara Bank',
    bicSwiftLabel: 'BIC/SWIFT',
    bankNameDrawerLabel: 'Nama Bank',
    bankAddressDrawerLabel: 'Alamat Bank',
    transactionRemarkDrawerLabel: 'Keterangan Transaksi',
    beneficiaryNameDrawerLabel: 'Nama Penerima',
    beneficiaryAddressDrawerLabel: 'Alamat Penerima',
    destinationAccountDrawerLabel: 'Rekening Tujuan',
    bankShortLabel: 'Bank',
    clientShortLabel: 'Klien',
    beneficiaryShortLabel: 'Penerima',
    // ClientKYC page
    kycProgressSavedToast: 'Progres disimpan',
    kycFailedToSaveToast: 'Gagal menyimpan: ',
    kycSubmittedForReviewToast: 'KYC dikirim untuk ditinjau!',
    kycFailedSubmitToast: 'Gagal mengirim: ',
    kycClientNotFound: 'Klien tidak ditemukan. Silakan hubungi dukungan.',
    kycSavingChangesFirst: 'Menyimpan perubahan terlebih dahulu...',

    // ===== Staff i18n batch =====
    // StaffKYC page
    staffKycHeaderTitle: 'Database KYC',
    staffKycHeaderSubtitle: 'Verifikasi Kenali Pelanggan',
    staffKycBackToResults: 'Kembali ke hasil',
    staffKycSearchTitle: 'Pencarian...',
    staffKycSearchPlaceholder: 'Cari...',
    staffKycSearchAllData: 'Cari Semua Data',
    staffKycIndividualTab: 'Individu',
    staffKycCorporateTab: 'Korporasi',
    staffKycNoResultsFound: 'Tidak ada hasil ditemukan',
    staffKycTypeLabelText: 'Jenis',
    staffKycSourceLabelText: 'Sumber',
    staffKycLoadDateLabelText: 'Tanggal Muat',
    staffKycTypeIndividual: 'Individu',
    staffKycTypeCorporate: 'Korporasi',
    staffKycTitleLabel: 'Gelar',
    staffKycJobTitleLabel: 'Jabatan',
    staffKycAliasLabel: 'Alias',
    staffKycNationalityLabel: 'Kewarganegaraan',
    staffKycPassportLabel: 'Paspor',
    staffKycIdentityNoLabel: 'Nomor Identitas',
    staffKycDobLabel: 'Tanggal Lahir',
    staffKycPobLabel: 'Tempat Lahir',
    staffKycAdditionalNamesLabel: 'Nama Tambahan',
    staffKycAddressLabel: 'Alamat',
    staffKycAdditionalInfoLabel: 'Informasi Tambahan',
    staffKycSourceListLabel: 'Daftar Sumber',
    staffKycEntryTypeLabel: 'Jenis Entri',
    staffKycLoadDateField: 'Tanggal Muat',
    // StaffPayeerAccounts
    payeerAccountsTitle: 'Akun Payeer',
    payeerGTransStaff: 'Staf GTrans',
    payeerAddAccount: 'Tambah Akun',
    payeerCurrencyHeader: 'Mata Uang',
    payeerAliasHeader: 'Alias',
    payeerAccountNumberHeader: 'Nomor Rekening',
    payeerBankNameHeader: 'Nama Bank',
    payeerCountryHeader: 'Negara',
    payeerStatusHeader: 'Status',
    payeerNoAccountsFound: 'Tidak ada akun ditemukan',
    payeerStatusActive: 'Aktif',
    payeerStatusInactive: 'Tidak Aktif',
    payeerEditAccount: 'Edit Akun',
    payeerAddPayeerAccount: 'Tambah Akun Payeer',
    payeerCurrencyLabel: 'Mata Uang *',
    payeerAliasLabel: 'Alias',
    payeerAliasPlaceholder: 'Nama singkat untuk mengidentifikasi akun ini',
    payeerAccountNumberLabel: 'Nomor Rekening *',
    payeerAccountNumberPlaceholder: 'Nomor rekening',
    payeerBankNameLabel: 'Nama Bank',
    payeerBankNamePlaceholder: 'Nama bank',
    payeerBankAddressLabel: 'Alamat Bank',
    payeerBankAddressPlaceholder: 'Alamat bank',
    payeerBankCorrAccountLabel: 'Rekening Koresponden Bank',
    payeerBankCorrAccountPlaceholder: 'Rekening koresponden',
    payeerBankBicLabel: 'BIC/SWIFT Bank',
    payeerBankBicPlaceholder: 'Kode BIC/SWIFT',
    payeerBankCountryLabel: 'Negara Bank',
    payeerBankCountryPlaceholder: 'Pilih negara',
    payeerActiveLabel: 'Aktif',
    payeerSavingDots: 'Menyimpan...',
    payeerSaveBtn: 'Simpan',
    payeerCancelBtn: 'Batal',
    payeerDeletingDots: 'Menghapus...',
    payeerDeleteBtn: 'Hapus',
    payeerAccountUpdated: 'Akun diperbarui',
    payeerAccountCreated: 'Akun dibuat',
    payeerAccountDeleted: 'Akun dihapus',
    payeerConfirmDelete: 'Apakah Anda yakin ingin menghapus akun ini?',
    payeerFillRequired: 'Harap isi semua bidang yang diperlukan',
    // StaffTransactionReport
    transTypePlaceholder: 'Jenis',
    transCurrencyPlaceholder: 'Mata Uang',
    transRiskPlaceholder: 'Risiko',
    transDttotPlaceholder: 'DTTOT',
    transDpppspmPlaceholder: 'DPPPSPM',
    // StaffCustomerReport
    custTypePlaceholder: 'Jenis Pelanggan',
    custCodePlaceholder: 'Jenis Kode',
    custPepPlaceholder: 'PEP',
    custCitizenshipPlaceholder: 'Kewarganegaraan',
    // StaffServiceAgreement
    saUpdatedSuccessfully: 'Berhasil diperbarui',
    saFailedToUpdate: 'Gagal memperbarui',
    saBadgeCreatedSuccess: 'Badge berhasil dibuat',
    saMasterDocUploaded: 'Dokumen utama diunggah',
    saFailedUploadMasterDoc: 'Gagal mengunggah dokumen utama',
    saMasterAgreementGenerated: 'Perjanjian Utama berhasil dibuat',
    saFailedGenerateMaster: 'Gagal membuat Perjanjian Utama',
    saAddNotesPlaceholder: 'Tambahkan catatan untuk klien...',
    // StaffClientRequests
    crSearchClientsPlaceholder: 'Cari klien...',
    crReasonForHoldPlaceholder: 'Alasan penahanan...',
    // StaffClients toasts
    clClientUpdatedToast: 'Klien diperbarui',
    clClientCreatedToast: 'Klien dibuat',
    clClientDeletedToast: 'Klien dihapus',
    clClientStatusUpdatedToast: 'Status klien diperbarui',
    clFailedSaveClientToast: 'Gagal menyimpan klien',
    clFailedDeleteClientToast: 'Gagal menghapus klien',
    // StaffActiveOrders
    aoOrdersDeletedToast: 'Pesanan dihapus',
    aoStatusChangedToText: 'Status diubah menjadi',
    aoNoOrdersSelected: 'Tidak ada pesanan yang dipilih',
    aoInstructionFileCreatedFor: 'Berkas instruksi dibuat untuk',
    aoOrderUpdatedToast: 'Pesanan diperbarui',
    // StaffComplyAdvantage
    caSearchFailedToast: 'Pencarian gagal',
    caSearchByNamePlaceholder: 'Cari berdasarkan nama atau ID eksternal...',
    // StaffExecutedOrders
    eoOrderUpdatedToast: 'Pesanan diperbarui',
    // Staff drawers
    drKycDecisionRecorded: 'Keputusan KYC berhasil dicatat',
    drFailedRecordDecision: 'Gagal mencatat keputusan',
    drAddCommentsAboutDecision: 'Tambahkan komentar tentang keputusan Anda...',
    drSelectAccountFromPayeer: 'Pilih akun dari Akun Payeer...',
    drSelectExecutingBank: 'Pilih bank pelaksana...',
    drSelectType: 'Pilih jenis...',
    drAdditionalNotesPlaceholder: 'Catatan tambahan...',
  },
};

export function getLanguage() {
  return localStorage.getItem('app_language') || 'en';
}

export function setLanguage(lang) {
  localStorage.setItem('app_language', lang);
  window.location.reload();
}

export function t(key, lang = null) {
  const language = lang || getLanguage();
  return translations[language]?.[key] || translations.en[key] || key;
}
